# CH02.1. **일반 행렬**

## 00. **작업 환경 설정**

#### 00.1. **라이브러리 호출 및 옵션 설정**

In [1]:
import numpy as np
import scipy

<b></b>

## 01. **선형 방정식 $ A\textbf{x} = \textbf{b} $ 에서 역행렬 연산보다 일반 연산이 효율적인 이유**

#### 01.1. **두 계산의 연산량은 모두 동일함**

#### **(1) 역행렬 연산량** : 
#### $ \hspace{0.15cm} $ ① 역행렬 $ A^{-1} $ 을 명시적으로 정의하는 연산량 : $ \, O(n^{3}) $
#### $ \hspace{0.15cm} $ ② $ \, A^{-1}\textbf{b} $ 의 연산량 : $ \, O(n^{2}) $

#### **(2) 일반 연산량** : 

#### $ \hspace{0.15cm} $ ① 가우스 소거(Gaussian elimination)의 연산량 : $ \, O(n^{3}) $
#### $ \hspace{0.15cm} $ ② LU 분해(decomposition)의 연산량 : 
#### $ \hspace{0.45cm} \cdot{} \, A = LU \, $ : $ \, O(n^{3}) $
#### $ \hspace{0.45cm} \cdot{} \, LU\textbf{x} = \textbf{b} \, $ : $ \, O(n^{3}) $

#### 01.2. **그러나 수치적 정확도를 고려했을 때, 역행렬 연산은 부정확해질 가능성이 존재함**

#### **(`EX`)** 컴퓨팅이 소수점 4개까지만 표현될경우, $ \, 3x = 6 $ 이라는 선형 방정식에서 해를 구하고자 할 때
#### $ \hspace{0.15cm} $ ① 역행렬을 구해 해를 찾는 경우 
#### $ \hspace{0.3cm} A^{-1} = 0.3333 \cdots{} \approx{} 0.3333 \Rightarrow{} x = 1.9998 = 0.1999E+01 $
#### $ \hspace{0.15cm} $ ② 일반 연산을 통해 해를 찾는 경우
#### $ \hspace{0.3cm} 3x = 6 \Rightarrow{} x = 2 $

#### 01.3. **일반적으로 $ \, A $ 가 희소 행렬(sparse matrix)일 경우 그 역행렬은 dense하나, LU 분해의 경우 그렇지 않을 경우가 커 연산이 더 효율적임**

<b></b>

## 02. **일반 행렬의 해**

#### 02.1. **행렬식(determinant) : `np.linalg.det()`**
#### $ \text{mat\_01} = \begin{bmatrix} 1&5&0 \\ 2&4&-1 \\ 0&-2&0 \end{bmatrix}, \;\; \det{}(\text{mat\_01}) = ? $

In [2]:
#(1)
mat_01 = np.array(object=[1, 5, 0, 2, 4, -1, 0, -2, 0], dtype=np.float64).reshape((3,3))

#(2)
mat_01

array([[ 1.,  5.,  0.],
       [ 2.,  4., -1.],
       [ 0., -2.,  0.]])

In [3]:
#(3)
np.linalg.det(a=mat_01)

-1.9999999999999998

In [4]:
#(4)
scipy.linalg.det(a=mat_01)

-2.0

#### 02.2. **역행렬(inverse matrix) : `np.linalg.inv()`**
#### $ \text{mat\_01} = \begin{bmatrix} 1&5&0 \\ 2&4&-1 \\ 0&-2&0 \end{bmatrix}, \;\; (\text{mat\_01})^{-1} = ? $

In [5]:
#(1) 
scipy.linalg.inv(a=mat_01)

array([[ 1. ,  0. ,  2.5],
       [ 0. ,  0. , -0.5],
       [ 2. , -1. ,  3. ]])

In [6]:
#(2)
np.linalg.inv(a=mat_01)

array([[ 1. ,  0. ,  2.5],
       [ 0. ,  0. , -0.5],
       [ 2. , -1. ,  3. ]])

#### 02.3. **일반 행렬의 해 구하기 : `np.linalg.solve()`**
#### $ \text{mat\_01} = \begin{bmatrix} 1&5&0 \\ 2&4&-1 \\ 0&-2&0 \end{bmatrix}, \;\; (\text{mat\_01})\textbf{x} = \textbf{b} = \begin{bmatrix} 1 \\ 1 \\ 1 \end{bmatrix}, \;\; \textbf{x} = ? $

In [22]:
#(1) 
vec_b = np.array(object=[1, 1, 1], dtype=np.float64)

#(2)
vec_b

array([1., 1., 1.])

In [23]:
#(3)
vec_x = np.linalg.solve(a=mat_01, b=vec_b)

#(4)
vec_x

array([ 3.5, -0.5,  4. ])

#### **(`PLUS`)** `assume_a` 파라미터 해석
#### $ \hspace{0.15cm} \cdot{} $ `gen` : 일반적인 행렬(뭔지 모름) $ \, \Rightarrow{} $ 
#### $ \hspace{0.15cm} \cdot{} $ `sym` : 대칭 행렬(symmetric matrix) $ \, \Rightarrow{} $
#### $ \hspace{0.15cm} \cdot{} $ `gesv` : $ \, \Rightarrow{} $ 
#### $ \hspace{0.15cm} \cdot{} $ `sysv` : $ \, \Rightarrow{} $ 
#### $ \hspace{0.15cm} \cdot{} $ `her` : 에르미트 행렬 $ \, \Rightarrow{} $ 
#### $ \hspace{0.15cm} \cdot{} $ `pos` : $ \, \Rightarrow{} $ 

#### **(`PLUS`)** (non-singular matrix)일 경우
#### **[CONTENTS]**

#### 02.4. **삼각 행렬의 해 구하기 : `np.linalg.solve_triangular()`**
#### $ \text{mat\_02} = \begin{bmatrix} 1&0&0&0 \\ 1&4&0&0 \\ 5&0&1&0 \\ 8&1&-2&2 \end{bmatrix}, \;\; (\text{mat\_02})\textbf{x} = \textbf{b} = \begin{bmatrix} 1 \\ 2 \\ 3 \\ 4 \end{bmatrix}, \;\; \textbf{x} = ? $

In [26]:
#(1)
mat_02 = np.array(object=[1, 0, 0, 0, 1, 4, 0, 0, 5, 0, 1, 0, 8, 1, -2, 2], dtype=np.float64).reshape(4,4)

#(2)
mat_02

array([[ 1.,  0.,  0.,  0.],
       [ 1.,  4.,  0.,  0.],
       [ 5.,  0.,  1.,  0.],
       [ 8.,  1., -2.,  2.]])

In [27]:
#(3)
vec_b = np.array(object=[1, 2, 3, 4], dtype=np.float64)

#(4)
vec_b

array([1., 2., 3., 4.])

In [39]:
#(5)
vec_x = scipy.linalg.solve_triangular(a=mat_02, b=vec_b, lower=True)

#(6)
vec_x

array([ 1.   ,  0.25 , -2.   , -4.125])

<b></b>

## 03. **해의 정확도 확인**

#### 03.1. **_ : `np.allclose()`**

In [41]:
#(1)
np.allclose(a=mat_02 @ vec_x, b=vec_b)

True

#### **(`PLUS`)** 
#### $ | x - y | \leq{} ( \epsilon_{1} + \epsilon{}_{2} \times{} |y| ) $
#### $ \epsilon{}_{1} : 10^{-8}, \;\; \epsilon{}_{2} : 10^{-5} $