# CH02.1. **일반 행렬**

## 00. **작업 환경 설정**

#### 00.1. **라이브러리 호출 및 옵션 설정**

In [1]:
import numpy as np
import scipy

<b></b>

## 01. **선형 방정식 $ A\textbf{x} = \textbf{b} $ 에서 역행렬 연산보다 일반 연산이 효율적인 이유**

#### 01.1. **두 계산의 연산량은 모두 동일함**

#### **(1) 역행렬 연산량** : 
#### $ \hspace{0.15cm} $ ① 역행렬 $ A^{-1} $ 을 명시적으로 정의하는 연산량 : $ \, O(n^{3}) $
#### $ \hspace{0.15cm} $ ② $ \, A^{-1}\textbf{b} $ 의 연산량 : $ \, O(n^{2}) $

#### **(2) 일반 연산량** : 

#### $ \hspace{0.15cm} $ ① 가우스 소거(Gaussian elimination)의 연산량 : $ \, O(n^{3}) $
#### $ \hspace{0.15cm} $ ② LU 분해(decomposition)의 연산량 : 
#### $ \hspace{0.45cm} \cdot{} \, A = LU \, $ : $ \, O(n^{3}) $
#### $ \hspace{0.45cm} \cdot{} \, LU\textbf{x} = \textbf{b} \, $ : $ \, O(n^{2}) $

#### 01.2. **그러나 수치적 정확도를 고려했을 때, 역행렬 연산은 부정확해질 가능성이 존재함** (backward error analysis)

#### **(`EX`)** 컴퓨팅이 소수점 $ \, 4 $ 개까지만 표현될경우, $ \, 3x = 6 $ 이라는 선형 방정식에서 해를 구하고자 할 때
#### $ \hspace{0.15cm} $ ① 역행렬을 구해 해를 찾는 경우 
#### $ \hspace{0.45cm} A^{-1} = 0.3333 \cdots{} \approx{} 0.3333 \Rightarrow{} x = 1.9998 = 0.1999E+01 $
#### $ \hspace{0.15cm} $ ② 일반 연산을 통해 해를 찾는 경우
#### $ \hspace{0.45cm} 3x = 6 \Rightarrow{} x = 2 $

#### 01.3. **행렬이 희소(sparse)할 경우 일반적으로 역행렬은 밀집(dense)하나, LU 분해의 경우 희소할 확률이 커 연산이 더 효율적임**

<b></b>

## 02. **일반 행렬 방정식의 해**

#### 02.1. **행렬식(determinant) : `np.linalg.det()`**
#### $ \text{mat\_01} = \begin{bmatrix} 1&5&0 \\ 2&4&-1 \\ 0&-2&0 \end{bmatrix}, \;\; \det{}(\text{mat\_01}) = ? $

#### **(`HOW?`)** LU 분해 후 행렬식을 구함, $ \;\; \det{}(A) = \det{}(L\times{}U) = \det{}(L) \times{} \det{}(U) $

In [2]:
#(1) Define `mat_01`
mat_01 = np.array(object=[1, 5, 0, 2, 4, -1, 0, -2, 0], dtype=np.float64).reshape((3,3))

#(2) Print `mat_01`
mat_01

array([[ 1.,  5.,  0.],
       [ 2.,  4., -1.],
       [ 0., -2.,  0.]])

In [3]:
#(3) Define determinent of `mat_01` (by numpy)
np.linalg.det(a=mat_01)

-1.9999999999999998

In [4]:
#(4) Define determinent of `mat_01` (by scipy)
scipy.linalg.det(a=mat_01)

-2.0

#### 02.2. **역행렬(inverse matrix) : `np.linalg.inv()`**
#### $ \text{mat\_01} = \begin{bmatrix} 1&5&0 \\ 2&4&-1 \\ 0&-2&0 \end{bmatrix}, \;\; (\text{mat\_01})^{-1} = ? $

#### **(`HOW?`)** LU 분해 후 역행렬을 구함, $ \;\; \det{}(L)\det{}(U)A^{-1} = I $

In [5]:
#(1) Define inverse matrix of `mat_01`
np.linalg.inv(a=mat_01)

array([[ 1. ,  0. ,  2.5],
       [ 0. ,  0. , -0.5],
       [ 2. , -1. ,  3. ]])

In [6]:
#(2) Define inverse matrix of `mat_01`
scipy.linalg.inv(a=mat_01)

array([[ 1. ,  0. ,  2.5],
       [ 0. ,  0. , -0.5],
       [ 2. , -1. ,  3. ]])

#### **(`PLUS`)** 특이 행렬(singular matrix)일 경우, 역행렬을 구할 수 없음
#### $ \text{mat\_02} = \begin{bmatrix} 1&3&4 \\ -4&2,&-6 \\ -3&-2&-7 \end{bmatrix}, \;\; (\text{mat\_02})^{-1} = ?  $

In [7]:
#(1)
mat_02 = np.array(object=[1, 3, 4, -4, 2, -6, -3, -2, -7], dtype=np.int64).reshape((3, 3))

#(2)
mat_02

array([[ 1,  3,  4],
       [-4,  2, -6],
       [-3, -2, -7]])

In [8]:
#(3)
try : 
    np.linalg.inv(a=mat_02)
except np.linalg.LinAlgError as error : 
    print(f'>> AN ERROR OCCURRED. ERROR MESSAGE IS "{error}".')

>> AN ERROR OCCURRED. ERROR MESSAGE IS "Singular matrix".


#### 02.3. **일반 행렬의 해 구하기 : `np.linalg.solve()`**
#### $ \text{mat\_01} = \begin{bmatrix} 1&5&0 \\ 2&4&-1 \\ 0&-2&0 \end{bmatrix}, \;\; (\text{mat\_01})\textbf{x} = \textbf{b} = \begin{bmatrix} 1 \\ 1 \\ 1 \end{bmatrix}, \;\; \textbf{x} = ? $

In [9]:
#(1) 
vec_b = np.array(object=[1, 1, 1], dtype=np.float64)

#(2)
vec_b

array([1., 1., 1.])

In [10]:
#(3)
vec_x = np.linalg.solve(a=mat_01, b=vec_b)

#(4)
vec_x

array([ 3.5, -0.5,  4. ])

#### **(`PLUS`)** `assume_a` 파라미터 해석
#### $ \hspace{0.15cm} \cdot{} $ `gen` : 일반적인 행렬(뭔지 모름) $ \, \Rightarrow{} $ LU 분해 ($ A = LU $)
#### $ \hspace{0.15cm} \cdot{} $ `sym` : 대칭 행렬(symmetric matrix; $ A = A^{T} $) $ \, \Rightarrow{} $ diagonal pivoting ($ A = LDL^{T} $)
#### $ \hspace{0.15cm} \cdot{} $ `her` : 에르미트 행렬(hermitian matrix; $ A = A^{*} $) $ \, \Rightarrow{} $ diagonal pivoting ($ A = LDL^{T} $)
#### $ \hspace{0.15cm} \cdot{} $ `pos` : 양의 정부호 행렬(positive definite matrix; $ \textbf{x}^{T}A\textbf{x} > 0 $) $ \, \Rightarrow{} $ Cholesky 분해 ($ A = R^{T}R = LL^{T} $)

#### 02.4. **삼각 행렬의 해 구하기 : `scipy.linalg.solve_triangular()`**
#### $ \text{mat\_02} = \begin{bmatrix} 1&0&0&0 \\ 1&4&0&0 \\ 5&0&1&0 \\ 8&1&-2&2 \end{bmatrix}, \;\; (\text{mat\_02})\textbf{x} = \textbf{b} = \begin{bmatrix} 1 \\ 2 \\ 3 \\ 4 \end{bmatrix}, \;\; \textbf{x} = ? $

In [11]:
#(1)
mat_02 = np.array(object=[1, 0, 0, 0, 1, 4, 0, 0, 5, 0, 1, 0, 8, 1, -2, 2], dtype=np.float64).reshape(4,4)

#(2)
mat_02

array([[ 1.,  0.,  0.,  0.],
       [ 1.,  4.,  0.,  0.],
       [ 5.,  0.,  1.,  0.],
       [ 8.,  1., -2.,  2.]])

In [12]:
#(3)
vec_b = np.array(object=[1, 2, 3, 4], dtype=np.float64)

#(4)
vec_b

array([1., 2., 3., 4.])

In [13]:
#(5)
vec_x = scipy.linalg.solve_triangular(a=mat_02, b=vec_b, lower=True)

#(6)
vec_x

array([ 1.   ,  0.25 , -2.   , -4.125])

<b></b>

## 03. **해의 정확도 확인**

#### 03.1. **절대오차와 상대오차**

#### **(1) 판단 기준** :
#### $ \hspace{0.15cm} \cdot{} \, | x - y | \leq{} (\epsilon_{1} + \epsilon{}_{2} \times{} |y| ) : \, $ 가깝다(close)
#### $ \hspace{0.15cm} \cdot{} \, | x - y | > (\epsilon_{1} + \epsilon{}_{2} \times{} |y| ) : \, $ 멀다(far; 다르다)

#### **(2) 절대오차(absolute tolerance)** : $ \, \epsilon{}_{1} = 10^{-8} $

##### **(3) 상대오차(relative tolerance)** : $ \, \epsilon{}_{2} \times{} y, \;\; \epsilon{}_{2} = 10^{-5} $

#### 03.2. **배열의 전체적 비교 : `np.allclose()`**

In [14]:
#(1)
np.allclose(a=mat_02 @ vec_x, b=vec_b)

True

#### 03.3. **배열의 요소간 비교 : `np.isclose()`**

In [15]:
#(1)
np.isclose(a=mat_02 @ vec_x, b=vec_b)

array([ True,  True,  True,  True])