## CH01.3. **기본 배열 생성**

## 00. **작업 환경 설정**

#### 00.1. **라이브러리 호출 및 옵션 설정**

In [1]:
import numpy as np

<b></b>

## 01. **항등행렬 생성**

#### 01.1. **정방항등행렬(단위항등행렬) 생성 : `np.identity()`**
#### $ \text{define mat\_01} = \begin{bmatrix} 1&0&0 \\ 0&1&0 \\ 0&0&1 \end{bmatrix}. $

In [2]:
#(1) Define `mat_01`
mat_01 = np.identity(n=3, dtype=np.int64)

#(2) Print `mat_01`
mat_01

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]])

#### 01.2. **정방항등행렬 생성 : `np.eye()`**
#### $ \text{define mat\_02} = \begin{bmatrix} 1&0&0 \\ 0&1&0 \\ 0&0&1 \end{bmatrix}. $

In [3]:
#(1) Define `mat_02`
mat_02 = np.eye(N=3, M=3, dtype=np.int64)

#(2) Print `mat_02`
mat_02

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]])

#### 01.3. **이동항등행렬(shift identity mat) 생성 : `np.eye(···, k)`** 
#### $ \text{define mat\_03} = \begin{bmatrix} 0&1&0&0 \\ 0&0&1&0 \\ 0&0&0&1 \end{bmatrix}. $

In [4]:
#(1) Define `mat_03`
mat_03 = np.eye(N=3, M=4, k=1, dtype=np.int32)

#(2) Print `mat_03`
mat_03

array([[0, 1, 0, 0],
       [0, 0, 1, 0],
       [0, 0, 0, 1]], dtype=int32)

#### **(`PLUS`)** 인자 `K`는 band id라고 정의함

<b></b>

## 02. **삼각행렬 생성**

#### 02.1. **단위 하삼각행렬 생성 : `np.tri()`**
#### $ \text{define mat\_04} = \begin{bmatrix} 1&0&0 \\ 1&1&0 \\ 1&1&1 \end{bmatrix}. $

In [5]:
#(1) Define `mat_04`
mat_04 = np.tri(N=3, M=3, k=0, dtype=np.int64)

#(2) Print `mat_04`
mat_04

array([[1, 0, 0],
       [1, 1, 0],
       [1, 1, 1]])

#### 02.2. **데이터 기반 하삼각행렬 생성 : `np.tril()`**
#### $ \text{define mat\_05} = \begin{bmatrix} 1&3&2&6 \\ 3&2.5&4&-3 \\ 1&-3.7&11&-2 \end{bmatrix}, \;\; \text{mat\_06} = \begin{bmatrix} 1&0&0&0 \\ 3&2.5&0&0 \\ 1&-3.7&11&0 \end{bmatrix}. $

In [6]:
#(1) Define `mat_05`
mat_05 = np.array(object=[[1, 3, 2, 6], [3, 2.5, 4, -3], [1, -3.7, 11, -2]])

#(2) Print `mat_05`
mat_05

array([[ 1. ,  3. ,  2. ,  6. ],
       [ 3. ,  2.5,  4. , -3. ],
       [ 1. , -3.7, 11. , -2. ]])

In [7]:
#(1) Define `mat_06`
mat_06 = np.tril(m=mat_05, k=0)

#(2) Print `mat_06`
mat_06

array([[ 1. ,  0. ,  0. ,  0. ],
       [ 3. ,  2.5,  0. ,  0. ],
       [ 1. , -3.7, 11. ,  0. ]])

#### 02.3. **기존 데이터 기반 상삼각행렬 생성 : `np.triu()`**
#### $ \text{mat\_05} = \begin{bmatrix} 1&3&2&6 \\ 3&2.5&4&-3 \\ 1&-3.7&11&-2 \end{bmatrix}, \;\; \text{define mat\_07} = \begin{bmatrix} 0&3&2&6 \\ 0&0&4&-3 \\ 0&0&0&-2 \end{bmatrix}. $

In [8]:
#(1) Define `mat_07`
mat_07 = np.triu(m=mat_05, k=1)

#(2) Print `mat_07`
mat_07

array([[ 0.,  3.,  2.,  6.],
       [ 0.,  0.,  4., -3.],
       [ 0.,  0.,  0., -2.]])

<b></b>

## 03. **기타 행렬 생성**

#### 03.1. **영행렬 생성 : `np.zeros()`**
#### $ \text{define mat\_08} = \begin{bmatrix} 0&0&0&0 \\ 0&0&0&0 \\ 0&0&0&0 \end{bmatrix}. $

In [9]:
#(1) Define `mat_08`
mat_08 = np.zeros(shape=(3, 4), dtype=np.int64)

#(2) Print `mat_08`
mat_08

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])

#### 03.2. **모든 성분이 1인 행렬 생성 : `np.ones()`**
#### $ \text{define mat\_09} = \begin{bmatrix} 1&1&1 \\ 1&1&1 \\ 1&1&1 \end{bmatrix}. $

In [10]:
#(1) Define `mat_09`
mat_09 = np.ones(shape=(3, 3), dtype=np.int64)

#(2) Print `mat_09`
mat_09

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])

#### 03.3. **모든 성분이 특정 값인 행렬 생성 : `np.full()`**
#### $ \text{define mat\_10} = \begin{bmatrix} 8&8&8&8&8 \\ 8&8&8&8&8 \\ 8&8&8&8&8 \\ 8&8&8&8&8 \\ 8&8&8&8&8 \end{bmatrix}. $

In [11]:
#(1) Define `mat_10`
mat_10 = np.full(shape=(5, 5), fill_value=8, dtype=np.int64)

#(2) Print `mat_10`
mat_10

array([[8, 8, 8, 8, 8],
       [8, 8, 8, 8, 8],
       [8, 8, 8, 8, 8],
       [8, 8, 8, 8, 8],
       [8, 8, 8, 8, 8]])

#### 03.4. **정방대각행렬 생성 : `np.diagflat()`**
#### $ \text{define mat\_11} = \begin{bmatrix} 1&0&0&0 \\ 0&2&0&0 \\ 0&0&6&0 \\ 0&0&0&7 \end{bmatrix}. $

In [12]:
#(1) Define `mat_11`
mat_11 = np.diagflat(v=[1, 2, 6, 7], k=0)

#(2) Print `mat_11`
mat_11

array([[1, 0, 0, 0],
       [0, 2, 0, 0],
       [0, 0, 6, 0],
       [0, 0, 0, 7]])

<b></b>

## 04. **난수 기반 행렬 생성**

#### 04.1. **균등분포를 따르는 정수인 행렬 생성 : `np.random.randint()`**
#### $ \text{define mat\_11} = \begin{bmatrix} a_{11}&a_{12}&a_{13} \\ a_{21}&a_{22}&a_{23} \\ a_{31}&a_{32}&a_{33} \end{bmatrix} \;\; \text{ where } \, a_{ik} \in{} \{ \mathbb{Z} \; | \; 1 \leqq{} \mathbb{Z} \leqq{} 10 \} \; \text{ and } \, a_{ik} \sim{} \text{Uniform}(0, 10) $

In [13]:
#(1) Define `mat_11`
mat_11 = np.random.randint(low=1, high=10, size=(3,3))

#(2) Print `mat_11`
mat_11

array([[3, 2, 7],
       [3, 4, 1],
       [4, 5, 1]])

#### 04.2. **$ 0 $ 과 $ 1 $ 사이의 균등분포를 따르는 실수인 행렬 생성 : `np.random.rand()`**
#### $ \text{define mat\_12} =\begin{bmatrix} a_{11}&a_{12}&a_{13} \\ a_{21}&a_{22}&a_{23} \\ a_{31}&a_{32}&a_{33} \end{bmatrix} \;\; \text{ where } \, a_{ik} \in{} \{ \mathbb{R} \; | \; 0 \leqq{} \mathbb{R} \leqq{} 1 \} \; \text{ and } \, a_{ik} \sim{} \text{Uniform}(0, 1) $

In [14]:
#(1) Define `mat_12`
mat_12 = np.random.rand(3, 3)

#(2) Print `mat_12`
mat_12

array([[0.58854337, 0.23400353, 0.95699017],
       [0.41688298, 0.22677534, 0.15757783],
       [0.18931488, 0.6742292 , 0.58210072]])

#### 04.3. **정규분포를 따르는 실수인 행렬 생성 : `np.random.normal()`**
#### $ \text{define mat\_13} = \begin{bmatrix} a_{11}&a_{12}&a_{13} \\ a_{21}&a_{22}&a_{23} \\ a_{31}&a_{32}&a_{33} \end{bmatrix} \;\; \text{ where } \, a_{ik} \in{} \{ \mathbb{R} \; | \; 0 \leqq{} \mathbb{R} \leqq{} 1 \} \; \text{ and } \, a_{ik} \sim{} N(\mu{}, \sigma{}^{2}) $

In [15]:
#(1) Define `mat_13`
mat_13 = np.random.normal(loc=0, scale=1, size=(3,3))

#(2) Print `mat_13`
mat_13

array([[ 2.43096306,  0.39587463,  0.55774587],
       [ 0.91679359,  0.93463195, -0.23722509],
       [ 0.66279141, -0.35140225,  0.20086561]])

#### 04.4. **표준정규분포를 따르는 실수인 행렬 생성 : `np.random.randn()`**
#### $ \text{define mat\_14} = \begin{bmatrix} a_{11}&a_{12}&a_{13} \\ a_{21}&a_{22}&a_{23} \\ a_{31}&a_{32}&a_{33} \end{bmatrix} \;\; \text{ where } \, a_{ik} \in{} \{ \mathbb{R} \; | \; 0 \leqq{} \mathbb{R} \leqq{} 1 \} \; \text{ and } \, a_{ik} \sim{} Z(0, 1) $

In [16]:
#(1) Define `mat_14`
mat_14 = np.random.randn(3, 3)

#(2) Print `mat_14`
mat_14

array([[ 0.40217254, -1.35057545, -1.1252656 ],
       [ 0.59459544, -1.34121083, -0.95639315],
       [-0.78790358, -0.24660682,  0.94996717]])