## CH01.3. **기본 배열 생성**

## 00. **작업 환경 설정**

#### 00.1. **라이브러리 호출 및 옵션 설정**

In [16]:
import numpy as np

<b></b>

## 01. **항등행렬 생성**

#### 01.1. **정방항등행렬(단위항등행렬) 생성 : `np.identity()`**
#### $ \text{define matrix\_01} = \begin{bmatrix} 1&0&0 \\ 0&1&0 \\ 0&0&1 \end{bmatrix}. $

In [17]:
#(1) Define `matrix_01`
matrix_01 = np.identity(n=3, dtype=np.int64)

#(2) Print `matrix_01`
matrix_01

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]])

#### 01.2. **정방항등행렬 생성 : `np.eye()`**
#### $ \text{define matrix\_02} = \begin{bmatrix} 1&0&0 \\ 0&1&0 \\ 0&0&1 \end{bmatrix}. $

In [18]:
#(1) Define `matrix_02`
matrix_02 = np.eye(N=3, M=3, dtype=np.int64)

#(2) Print `matrix_02`
matrix_02

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]])

#### 01.3. **이동항등행렬(shift identity matrix) 생성 : `np.eye(···, k)`** 
#### $ \text{define matrix\_03} = \begin{bmatrix} 0&1&0&0 \\ 0&0&1&0 \\ 0&0&0&1 \end{bmatrix}. $

In [19]:
#(1) Define `matrix_03`
matrix_03 = np.eye(N=3, M=4, k=1, dtype=np.int32)

#(2) Print `matrix_03`
matrix_03

array([[0, 1, 0, 0],
       [0, 0, 1, 0],
       [0, 0, 0, 1]], dtype=int32)

#### **(`PLUS`)** 인자 `K`는 band id라고 정의함

<b></b>

## 02. **삼각행렬 생성**

#### 02.1. **단위 하삼각행렬 생성 : `np.tri()`**
#### $ \text{define matrix\_04} = \begin{bmatrix} 1&0&0 \\ 1&1&0 \\ 1&1&1 \end{bmatrix}. $

In [20]:
#(1) Define `matrix_04`
matrix_04 = np.tri(N=3, M=3, k=0, dtype=np.int64)

#(2) Print `matrix_04`
matrix_04

array([[1, 0, 0],
       [1, 1, 0],
       [1, 1, 1]])

#### 02.2. **데이터 기반 하삼각행렬 생성 : `np.tril()`**
#### $ \text{define matrix\_05} = \begin{bmatrix} 1&3&2&6 \\ 3&2.5&4&-3 \\ 1&-3.7&11&-2 \end{bmatrix}, \;\; \text{matrix\_06} = \begin{bmatrix} 1&0&0&0 \\ 3&2.5&0&0 \\ 1&-3.7&11&0 \end{bmatrix}. $

In [21]:
#(1) Define `matrix_05`
matrix_05 = np.array(object=[[1, 3, 2, 6], [3, 2.5, 4, -3], [1, -3.7, 11, -2]])

#(2) Print `matrix_05`
matrix_05

array([[ 1. ,  3. ,  2. ,  6. ],
       [ 3. ,  2.5,  4. , -3. ],
       [ 1. , -3.7, 11. , -2. ]])

In [22]:
#(1) Define `matrix_06`
matrix_06 = np.tril(m=matrix_05, k=0)

#(2) Print `matrix_06`
matrix_06

array([[ 1. ,  0. ,  0. ,  0. ],
       [ 3. ,  2.5,  0. ,  0. ],
       [ 1. , -3.7, 11. ,  0. ]])

#### 02.3. **기존 데이터 기반 상삼각행렬 생성 : `np.triu()`**
#### $ \text{matrix\_05} = \begin{bmatrix} 1&3&2&6 \\ 3&2.5&4&-3 \\ 1&-3.7&11&-2 \end{bmatrix}, \;\; \text{define matrix\_07} = \begin{bmatrix} 0&3&2&6 \\ 0&0&4&-3 \\ 0&0&0&-2 \end{bmatrix}. $

In [23]:
#(1) Define `matrix_07`
matrix_07 = np.triu(m=matrix_05, k=1)

#(2) Print `matrix_07`
matrix_07

array([[ 0.,  3.,  2.,  6.],
       [ 0.,  0.,  4., -3.],
       [ 0.,  0.,  0., -2.]])

<b></b>

## 03. **기타 행렬 생성**

#### 03.1. **영행렬 생성 : `np.zeros()`**
#### $ \text{define matrix\_08} = \begin{bmatrix} 0&0&0&0 \\ 0&0&0&0 \\ 0&0&0&0 \end{bmatrix}. $

In [24]:
#(1) Define `matrix_08`
matrix_08 = np.zeros(shape=(3, 4), dtype=np.int64)

#(2) Print `matrix_08`
matrix_08

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])

#### 03.2. **모든 성분이 1인 행렬 생성 : `np.ones()`**
#### $ \text{define matrix\_09} = \begin{bmatrix} 1&1&1 \\ 1&1&1 \\ 1&1&1 \end{bmatrix}. $

In [25]:
#(1) Define `matrix_09`
matrix_09 = np.ones(shape=(3, 3), dtype=np.int64)

#(2) Print `matrix_09`
matrix_09

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])

#### 03.3. **모든 성분이 특정 값인 행렬 생성 : `np.full()`**
#### $ \text{define matrix\_10} = \begin{bmatrix} 8&8&8&8&8 \\ 8&8&8&8&8 \\ 8&8&8&8&8 \\ 8&8&8&8&8 \\ 8&8&8&8&8 \end{bmatrix}. $

In [26]:
#(1) Define `matrix_10`
matrix_10 = np.full(shape=(5, 5), fill_value=8, dtype=np.int64)

#(2) Print `matrix_10`
matrix_10

array([[8, 8, 8, 8, 8],
       [8, 8, 8, 8, 8],
       [8, 8, 8, 8, 8],
       [8, 8, 8, 8, 8],
       [8, 8, 8, 8, 8]])

#### 03.4. **정방대각행렬 생성 : `np.diagflat()`**
#### $ \text{define matrix\_11} = \begin{bmatrix} 1&0&0&0 \\ 0&2&0&0 \\ 0&0&6&0 \\ 0&0&0&7 \end{bmatrix}. $

In [27]:
#(1) Define `matrix_11`
matrix_11 = np.diagflat(v=[1, 2, 6, 7], k=0)

#(2) Print `matrix_11`
matrix_11

array([[1, 0, 0, 0],
       [0, 2, 0, 0],
       [0, 0, 6, 0],
       [0, 0, 0, 7]])

<b></b>

## 04. **난수 기반 행렬 생성**

#### 04.1. **균등분포를 따르는 정수인 행렬 생성 : `np.random.randint()`**
#### $ \text{define matrix\_11} = \begin{bmatrix} a_{11}&a_{12}&a_{13} \\ a_{21}&a_{22}&a_{23} \\ a_{31}&a_{32}&a_{33} \end{bmatrix} \;\; \text{ where } \, a_{ik} \in{} \{ \mathbb{Z} \; | \; 1 \leqq{} \mathbb{Z} \leqq{} 10 \} \; \text{ and } \, a_{ik} \sim{} \text{Uniform}(0, 10) $

In [28]:
#(1) Define `matrix_11`
matrix_11 = np.random.randint(low=1, high=10, size=(3,3))

#(2) Print `matrix_11`
matrix_11

array([[6, 9, 4],
       [7, 8, 9],
       [9, 2, 1]])

#### 04.2. **$ 0 $ 과 $ 1 $ 사이의 균등분포를 따르는 실수인 행렬 생성 : `np.random.rand()`**
#### $ \text{define matrix\_12} =\begin{bmatrix} a_{11}&a_{12}&a_{13} \\ a_{21}&a_{22}&a_{23} \\ a_{31}&a_{32}&a_{33} \end{bmatrix} \;\; \text{ where } \, a_{ik} \in{} \{ \mathbb{R} \; | \; 0 \leqq{} \mathbb{R} \leqq{} 1 \} \; \text{ and } \, a_{ik} \sim{} \text{Uniform}(0, 1) $

In [29]:
#(1) Define `matrix_12`
matrix_12 = np.random.rand(3, 3)

#(2) Print `matrix_12`
matrix_12

array([[0.92065502, 0.56183961, 0.98524443],
       [0.7064625 , 0.80490051, 0.74182336],
       [0.03117722, 0.56479419, 0.66679569]])

#### 04.3. **정규분포를 따르는 실수인 행렬 생성 : `np.random.normal()`**
#### $ \text{define matrix\_13} = \begin{bmatrix} a_{11}&a_{12}&a_{13} \\ a_{21}&a_{22}&a_{23} \\ a_{31}&a_{32}&a_{33} \end{bmatrix} \;\; \text{ where } \, a_{ik} \in{} \{ \mathbb{R} \; | \; 0 \leqq{} \mathbb{R} \leqq{} 1 \} \; \text{ and } \, a_{ik} \sim{} N(\mu{}, \sigma{}^{2}) $

In [30]:
#(1) Define `matrix_13`
matrix_13 = np.random.normal(loc=0, scale=1, size=(3,3))

#(2) Print `matrix_13`
matrix_13

array([[ 0.6434122 ,  0.50024934, -0.47149534],
       [ 1.7499768 ,  2.15323835, -0.25894683],
       [-0.71809634, -1.35233516,  1.21124891]])

#### 04.4. **표준정규분포를 따르는 실수인 행렬 생성 : `np.random.randn()`**
#### $ \text{define matrix\_14} = \begin{bmatrix} a_{11}&a_{12}&a_{13} \\ a_{21}&a_{22}&a_{23} \\ a_{31}&a_{32}&a_{33} \end{bmatrix} \;\; \text{ where } \, a_{ik} \in{} \{ \mathbb{R} \; | \; 0 \leqq{} \mathbb{R} \leqq{} 1 \} \; \text{ and } \, a_{ik} \sim{} Z(0, 1) $

In [31]:
#(1) Define `matrix_14`
matrix_14 = np.random.randn(3, 3)

#(2) Print `matrix_14`
matrix_14

array([[-0.81369682, -0.07455861, -1.53925959],
       [ 1.45587653,  1.73773739,  0.99352668],
       [-0.70364519,  2.06216585, -0.36871186]])