## CH01.4. **배열 조작**

## 00. **작업 환경 설정**

#### 00.1. **라이브러리 호출 및 옵션 설정**

In [1]:
import numpy as np

<b></b>

## 01. **배열 복사**

#### 01.1. **배열 복사 : `.copy()`**
#### $ \text{mat\_01} = \begin{bmatrix} 1&2&3 \\ 2&3&1 \\ 3&4&6 \end{bmatrix}, \;\; \text{mat\_02} = \text{mat\_01}, \;\; \text{define mat\_02}. $

In [2]:
#(1) Define `mat_01`
mat_01 = np.array(object=[[1, 2, 3], [2, 3, 1], [3, 4, 6]], dtype=np.int64)

#(2) Print `mat_01`
mat_01

array([[1, 2, 3],
       [2, 3, 1],
       [3, 4, 6]])

In [3]:
#(3) Copy `mat_01`
mat_02 = mat_01.copy()

#(4) Print `mat_02`
mat_02

array([[1, 2, 3],
       [2, 3, 1],
       [3, 4, 6]])

#### **(`PLUS`)** 바로 변수를 할당하는 경우, 같은 메모리(공간)을 참조하기 때문에 영향을 받음

In [4]:
#(1) Define `mat_03`
mat_03 = mat_01 

#(2) Print `mat_03`
mat_03

array([[1, 2, 3],
       [2, 3, 1],
       [3, 4, 6]])

In [5]:
#(3) Modify entry of `mat_03` 
mat_03[0, 0] = 32

#(4) Print `mat_03`
mat_03

array([[32,  2,  3],
       [ 2,  3,  1],
       [ 3,  4,  6]])

In [6]:
#(5) Print `mat_01`
mat_01

array([[32,  2,  3],
       [ 2,  3,  1],
       [ 3,  4,  6]])

<b></b>

## 02. **배열 형태 변환**

#### 02.1. **배열 n차원 변환 : `np.reshape()`**
#### $ \text{mat\_04} = \begin{bmatrix} 1&2&3&2 \\ 2&3&1&4 \\ 3&4&6&8 \end{bmatrix}, \;\; \text{mat\_05} = \begin{bmatrix} 1&2&3&2&2&3 \\ 1&4&3&4&6&8 \end{bmatrix}, \;\; \text{define mat\_05}. $

In [7]:
#(1) Define `mat_04`
mat_04 = np.array(object=[[1, 2, 3, 2], [2, 3, 1, 4], [3, 4, 6, 8]], dtype=np.int64)

#(2) Print `mat_04`
mat_04

array([[1, 2, 3, 2],
       [2, 3, 1, 4],
       [3, 4, 6, 8]])

In [8]:
#(3) Define `mat_05`
mat_05 = np.reshape(a=mat_04.copy(), newshape=(2, 6))

#(4) Print `mat_05`
mat_05

array([[1, 2, 3, 2, 2, 3],
       [1, 4, 3, 4, 6, 8]])

#### 02.2. **배열 전치 : `.transpose()`**
#### $ \text{mat\_04} = \begin{bmatrix} 1&2&3&2 \\ 2&3&1&4 \\ 3&4&6&8 \end{bmatrix}, \;\; \text{mat\_06} = (\text{mat\_04})^{T}, \;\; \text{define mat\_06}. $

In [9]:
#(1) Transpose `mat_04`
mat_06 = mat_04.transpose()

#(2) Print `mat_05`
mat_06

array([[1, 2, 3],
       [2, 3, 4],
       [3, 1, 6],
       [2, 4, 8]])

#### 02.3. **1차원 벡터 변환 : `.flatten()`**
#### $ \text{mat\_04} = \begin{bmatrix} 1&2&3&2 \\ 2&3&1&4 \\ 3&4&6&8 \end{bmatrix}, \;\; \text{vec\_01} = \begin{bmatrix} 1&2&3&2&\cdots{}&6&8 \end{bmatrix}, \;\; \text{define vec\_01}. $

In [10]:
#(1) Define `vec_01`
vec_01 = mat_04.flatten()

#(2) Print `vec_01`
vec_01

array([1, 2, 3, 2, 2, 3, 1, 4, 3, 4, 6, 8])

#### **(`PLUS`)** `.flatten()` 메서드는 `np.ravel()` 함수와 동일한 결과를 반환함

In [11]:
#(1) Define `vec_02`
vec_02 = np.ravel(a=mat_04)

#(2) Print `vec_02`
vec_02

array([1, 2, 3, 2, 2, 3, 1, 4, 3, 4, 6, 8])

<b></b>

## 02. **대각 성분 조작**

#### 02.1. **대각 성분 반환 : `np.diag()`**
#### $ \text{mat\_04} = \begin{bmatrix} 1&2&3&2 \\ 2&3&1&4 \\ 3&4&6&8 \end{bmatrix}, \;\; \begin{bmatrix} a_{11} \\ a_{22} \\ a_{23} \end{bmatrix} = ? $

In [12]:
#(1) Print diagonal entry of `mat_04` 
np.diag(v=mat_04, k=0)

array([1, 3, 6])

#### 02.2. **대각 성분 합 반환 : `np.trace()`**
#### $ \text{mat\_04} = \begin{bmatrix} 1&2&3&2 \\ 2&3&1&4 \\ 3&4&6&8 \end{bmatrix}, \;\; a_{11}+a_{22}+a_{23} = ? $

In [13]:
#(1) Print diagonal entry sum of `mat_04`
np.trace(a=mat_04)

10

<b></b>

## 04. **배열 결합**

#### 04.1. **수평 배열 결합 : `np.hstack()`**
#### $ \text{mat\_08} = \begin{bmatrix} \text{mat\_01} & \text{mat\_02} \end{bmatrix}, \;\; \text{define mat\_08}. $

In [14]:
#(1) Define `mat_08`
mat_08 = np.hstack(tup=(mat_01, mat_02))

#(2) Print `mat_08`
mat_08

array([[32,  2,  3,  1,  2,  3],
       [ 2,  3,  1,  2,  3,  1],
       [ 3,  4,  6,  3,  4,  6]])

#### 04.2. **수직 배열 결합 : `np.vstack()`**
#### $ \text{mat\_09} = \begin{bmatrix} \text{mat\_01} \\ \text{mat\_02} \end{bmatrix}, \;\; \text{define mat\_09}. $

In [15]:
#(1) Define `mat_09`
mat_09 = np.vstack(tup=(mat_01, mat_02))

#(2) Print `mat_09`
mat_09

array([[32,  2,  3],
       [ 2,  3,  1],
       [ 3,  4,  6],
       [ 1,  2,  3],
       [ 2,  3,  1],
       [ 3,  4,  6]])

<b></b>

## 05. **배열 값 반환**

#### 05.1. **실수부반환 : `.real`**
#### $ \text{mat\_10} = \begin{bmatrix} 1+2i&3&-4i \\ 1-3j&2&0 \\ 0&i&3+6i \end{bmatrix}, \;\; \text{return real number of mat\_10}. $

In [16]:
#(1) Define `mat_10`
mat_10 = np.array(object=[[1+2j, 3, -4j], [1-3j, 2, 0], [0, 1j, 3+6j]], dtype=np.complex128)

#(2) Print `mat_10`
mat_10

array([[ 1.+2.j,  3.+0.j, -0.-4.j],
       [ 1.-3.j,  2.+0.j,  0.+0.j],
       [ 0.+0.j,  0.+1.j,  3.+6.j]])

In [17]:
#(3) Print real Number of `mat_10`
mat_10.real

array([[ 1.,  3., -0.],
       [ 1.,  2.,  0.],
       [ 0.,  0.,  3.]])

#### 05.2. **허수부 반환 : `.imag`**
#### $ \text{mat\_10} = \begin{bmatrix} 1+2i&3&-4i \\ 1-3j&2&0 \\ 0&i&3+6i \end{bmatrix}, \;\; \text{return complex number of mat\_10}. $

In [18]:
#(1) Print complex number of `mat_10`
mat_10.imag

array([[ 2.,  0., -4.],
       [-3.,  0.,  0.],
       [ 0.,  1.,  6.]])

#### 05.3. **허수부 복소켤레 반환 : `.conjugate()`**
#### $ \text{mat\_10} \begin{bmatrix} 1+2i&3&-4i \\ 1-3j&2&0 \\ 0&i&3+6i \end{bmatrix}, \;\; \text{return complex conjugate of mat\_10}. $

In [19]:
#(1) Print complex conjugate of `mat_10`
mat_10.conjugate()

array([[ 1.-2.j,  3.-0.j, -0.+4.j],
       [ 1.+3.j,  2.-0.j,  0.-0.j],
       [ 0.-0.j,  0.-1.j,  3.-6.j]])