# CH01.5. **배열 연산**

## 00. **작업 환경 설정**

#### 00.1. **라이브러리 호출 및 옵션 설정**

In [21]:
import numpy as np

<b></b>

## 01. **배열의 합**

#### 01.1. **행렬-스칼라 합** (By broad-casting)
#### $ \text{mat\_01} = \begin{bmatrix} 1&3&-5 \\ 2&0&-4 \\ 3&2&1 \end{bmatrix}, \;\; \begin{bmatrix} 3&3&3 \\ 3&3&3 \\ 3&3&3 \end{bmatrix} + \text{mat\_01} = ? $

In [22]:
#(1) Define `mat_01`
mat_01 = np.array(object=[[1, 3, -5], [2, 0, -4], [3, 2, 1]], dtype=np.int64)

#(2) Print `mat_01`
mat_01

array([[ 1,  3, -5],
       [ 2,  0, -4],
       [ 3,  2,  1]])

In [23]:
#(3) Print `mat_01` + 3
mat_01 + 3

array([[ 4,  6, -2],
       [ 5,  3, -1],
       [ 6,  5,  4]])

#### **(`PLUS`)** 브로드 캐스팅(Broad Casting) : 
#### $ \hspace{0.15cm} \cdot{} $ 더 작은 배열을 자동으로 더 큰 배열의 크기에 맞춰 확장하는 메커니즘
#### $ \hspace{0.15cm} \cdot{} $ 연산기호 `*`을 이용하면 브로드캐스팅을 이용하여 연산 처리

#### 01.2. **행렬-벡터 합**
#### $ \text{mat\_01} = \begin{bmatrix} 1&3&-5 \\ 2&0&-4 \\ 3&2&1 \end{bmatrix}, \;\; \text{vec\_01} = \begin{bmatrix} -3&2&0 \end{bmatrix}, \;\; \begin{bmatrix} \text{vec\_01} \\ \text{vec\_01} \\ \text{vec\_01} \end{bmatrix} + \text{mat\_01} = ? $

In [24]:
#(1) Define `vec_01`
vec_01 = np.array(object=[-3, 2, 0])

#(2) Print `vec_01`
vec_01

array([-3,  2,  0])

In [25]:
#(3) Print `mat_01` + `vec_01`
mat_01 + vec_01

array([[-2,  5, -5],
       [-1,  2, -4],
       [ 0,  4,  1]])

#### **(`PLUS`)** 두 배열의 사이즈들의 값 중 한 개라도 일치하면 연산이 되지만, 그렇지 않으면 연산되지 않음

In [26]:
#(1) Define `vec_02`
vec_02 = np.array(object=[1, 3], dtype=np.int64)

#(2) Print `vec_01` + `vec_02`
try : 
    mat_01 + vec_02
except ValueError as error : 
    print(f'>> AN ERROR OCCURRED. ERROR MESSAGE IS "{error}".')

>> AN ERROR OCCURRED. ERROR MESSAGE IS "operands could not be broadcast together with shapes (3,3) (2,) ".


#### 01.3. **행렬-행렬 합**
#### $ \text{mat\_01} = \begin{bmatrix} 1&3&-5 \\ 2&0&-4 \\ 3&2&1 \end{bmatrix}, \;\; \text{mat\_02} = \begin{bmatrix} 3&0&2 \\ 2&0&0 \\ 1.1&-3&6.5 \end{bmatrix}, \;\; \text{mat\_01} + \text{mat\_02} = ? $

In [27]:
#(1) Define `mat_02`
mat_02 = np.array(object=[[3, 0, 2], [2, 0, 0], [1.1, -3, 6.5]])

#(2) Print `mat_02`
mat_02

array([[ 3. ,  0. ,  2. ],
       [ 2. ,  0. ,  0. ],
       [ 1.1, -3. ,  6.5]])

In [28]:
#(3) Print `mat_01` + `mat_02`
mat_01 + mat_02

array([[ 4. ,  3. , -3. ],
       [ 4. ,  0. , -4. ],
       [ 4.1, -1. ,  7.5]])

<b></b>

## 02. **배열의 곱**

#### 02.1. **행렬-스칼라 곱**
#### $ \text{mat\_01} = \begin{bmatrix} 1&3&-5 \\ 2&0&-4 \\ 3&2&1 \end{bmatrix}, \;\; 3 \times{} \text{mat\_01} = ? $

In [29]:
#(1) Print 3 * `mat_01`
3 * mat_01

array([[  3,   9, -15],
       [  6,   0, -12],
       [  9,   6,   3]])

#### 02.3. **행렬-벡터 곱 : `np.matmul()` or `@`**
#### $ \text{mat\_01} = \begin{bmatrix} 1&3&-5 \\ 2&0&-4 \\ 3&2&1 \end{bmatrix}, \;\; \text{vec\_01} = \begin{bmatrix} -3&2&0 \end{bmatrix}, \;\; \text{vec\_01} \times{} \text{mat\_01} = ? $

In [30]:
#(1) Print `vec_01` * `mat_01`
vec_01 @ mat_01

array([ 1, -9,  7])

In [31]:
#(2) Print `vec_01` * `mat_01`
np.matmul(vec_01, mat_01)

array([ 1, -9,  7])

#### 02.3. **행렬-행렬 곱 : `np.matmul()` or `@`**
#### $ \text{mat\_01} = \begin{bmatrix} 1&3&-5 \\ 2&0&-4 \\ 3&2&1 \end{bmatrix}, \;\; \text{mat\_02} = \begin{bmatrix} 3&0&2 \\ 2&0&0 \\ 1.1&-3&6.5 \end{bmatrix}, \;\; \text{mat\_01} \times{} \text{mat\_02} = ? $

In [32]:
#(1) Print `mat_01` @ `mat_02``
mat_01 @ mat_02

array([[  3.5,  15. , -30.5],
       [  1.6,  12. , -22. ],
       [ 14.1,  -3. ,  12.5]])

In [33]:
#(2) Print `mat_01` @ `mat_02``
np.matmul(mat_01, mat_02)

array([[  3.5,  15. , -30.5],
       [  1.6,  12. , -22. ],
       [ 14.1,  -3. ,  12.5]])

#### **(`PLUS`)** 브로드캐스팅을 이용할 경우

In [34]:
#(1) Print `mat_01` * `mat_02`
mat_01 * mat_02

array([[  3. ,   0. , -10. ],
       [  4. ,   0. ,  -0. ],
       [  3.3,  -6. ,   6.5]])

<b></b>

## 03. **배열의 기타 연산**

#### 03.1. **내적(Inner product) : `np.vdot()`**
#### $ \text{vec\_01} = \begin{bmatrix} -3&2&0 \end{bmatrix}, \;\; \text{vec\_03} = \begin{bmatrix} 0&8&2 \end{bmatrix}, \;\; \text{vec\_01} \cdot{} \text{vec\_03} = ? $

In [35]:
#(1) Define `vec_03`
vec_03 = np.array(object=[0, 8, 2])

#(2) Print `vec_03`
vec_03

array([0, 8, 2])

In [36]:
#(3) Print inner product of `mat_01` and `mat_02`
np.vdot(vec_01, vec_03)

16

#### 03.2. **외적-벡터곱(Cross product) : `np.cross()`**
#### $ \text{vec\_01} = \begin{bmatrix} -3&2&0 \end{bmatrix}, \;\; \text{vec\_03} = \begin{bmatrix} 0&8&2 \end{bmatrix}, \;\; \text{vec\_01} \times{} \text{vec\_03} = ? $

In [37]:
#(3) Print cross-product of `vec_01` and `vec_02`
np.cross(a=vec_01, b=vec_02)

array([  0,   0, -11])

#### 03.3. **외적-텐서곱(Outer Product) : `np.outer()`**
#### $ \text{vec\_01} = \begin{bmatrix} -3&2&0 \end{bmatrix}, \;\; \text{vec\_03} = \begin{bmatrix} 0&8&2 \end{bmatrix}, \;\; \text{vec\_01} \otimes{} \text{vec\_03} = ? $

In [38]:
#(1) Print outer-product of `vec_01` and `vec_02`
np.outer(a=vec_01, b=vec_02)

array([[-3, -9],
       [ 2,  6],
       [ 0,  0]])

<b></b>

## 04. **벡터의 길이 ; 놈(Norm)**

#### 04.1. **맨하탄 놈(Manhattan norm); L1 놈**
#### $ \text{L1 Norm} = \lVert{} \textbf{x} \rVert{}_{1} = \sum{}_{i=1}^{n} |\textbf{x}_{i} |, \;\; \lVert{} \text{vec\_01} \rVert{}_{1} = ? $

In [39]:
#(1) Print l1-norm of `vec_01`
np.linalg.norm(x=vec_01, ord=1)

5.0

#### 04.2. **유클라디안 놈(Euclidean); L2 놈**
#### $ \text{L2 Norm} = \lVert{} \textbf{x} \rVert{}_{2} = \sum{}_{i=1}^{n} \sqrt{\textbf{x}_{i}^{2}}, \;\; \lVert{} \text{vec\_01} \rVert{}_{2} = ? $

In [40]:
#(2) Print l2-norm of `vec_01`
np.linalg.norm(x=vec_01, ord=2)

3.605551275463989