## CH2.1. **배열 표현**

## 00. **SET WORK ENVORINMENT**

#### 00.1. **IMPORT PACKAGES AND SET OPTIONS**

In [1]:
import numpy as np

<b></b>

## 01. **데이터 정밀도**

#### **01.1. 정밀도(Precision)**
##### **(1)** 숫자 $ {{1}\over{3}} = 0.333 \cdots{} $ 를 컴퓨터에 저장하고자할 경우, 무한 소수를 저장할 수 없기에 근사값으로 저장하는데, 
##### $ \;\;\;\; $ precision은 유효숫자의 자리수를 의미
##### **(2)** 일반적으로 precision이 높아질수록 더 많은 메모리 공간이 필요
<b></b>

## 02. **벡터(1D-array) 표현** 

#### 02.1. **변수 할당 : `np.array()`**
#### vector_01 $ \; = \begin{bmatrix} 7 \\ 5 \\ 3 \end{bmatrix} $

In [2]:
#(1) assign `vector_01`
vector_01 = np.array(object=[7, 5, 3])

#(2) print `vector_01`
vector_01

array([7, 5, 3])

**(MEMO)** numpy 벡터는 **일반적으로** 행벡터, 열벡터를 구분하지 않음

#### 02.2. **사이즈 확인 : `.shape`**

In [3]:
#(1) print `vector_01` shape
vector_01.shape

(3,)

**(MEMO)** 벡터의 경우 numpy 패키지에서는 행렬과 구분하기 위하여 열 사이즈가 생략됨

#### 02.3. **인덱싱 : `[n]`**
#### vector_01 $ \; = \begin{bmatrix} 7 \\ 5 \\ 3 \end{bmatrix} = \begin{bmatrix} a_{11} \\ a_{21} \\ a_{31} \end{bmatrix}, \; a_{31} = ? $

In [4]:
#(1) print `vector_01` indexing
vector_01[2] 

3

**(MEMO)** 파이썬에서는 기본 인덱싱이 0부터 시작함

#### 02.4. **슬라이싱 : `[n:m]`**
#### vector_01 $ \; = \begin{bmatrix} 7 \\ 5 \\ 3 \end{bmatrix} = \begin{bmatrix} a_{11} \\ a_{21} \\ a_{31} \end{bmatrix}, \; \begin{bmatrix} a_{21} \\ a_{31} \end{bmatrix} = ? $

In [5]:
#(1) print `vector_01` slicing
vector_01[1:3] 

array([5, 3])

## 03. **행렬(2D-array) 표현**

#### 03.1. **변수 할당 : `np.array()`**
#### matrix_01 $ \; = \begin{bmatrix} 1&2.5&3 \\ -1&-2&-1.5 \\ 4&5.5&6 \end{bmatrix} $

In [6]:
#(1) assign `matrix_01`
matrix_01 = np.array(object=[[1, 2.5, 3], [-1, -2, -1.5], [4, 5.5, 6]])

#(2) print `matrix_01`
matrix_01

array([[ 1. ,  2.5,  3. ],
       [-1. , -2. , -1.5],
       [ 4. ,  5.5,  6. ]])

**(MEMO)** 행 벡터 단위로 `np.array()` 함수에 배열을 할당해야함

#### 02.2. **사이즈 확인 : `.shape`**

In [7]:
#(2) print `matrix_01` shape
matrix_01.shape

(3, 3)

#### 03.3. **인덱싱 : `[n]`**
#### matrix_01 $ \; = \begin{bmatrix} 1&2.5&3 \\ -1&-2&-1.5 \\ 4&5.5&6 \end{bmatrix} = \begin{bmatrix} a_{11}&a_{12}&a_{13} \\ a_{21}&a_{22}&a_{23} \\ a_{31}&a_{32}&a_{33} \end{bmatrix} , \; a_{23} = ? $

In [8]:
#(1) print `matrix_01` indexingg
matrix_01[0, 1] 

# OR
# matrix_01[0][1]

2.5

#### 03.4. **슬라이싱 : `[n:m]`**
#### matrix_01 $ \; = \begin{bmatrix} 1&2.5&3 \\ -1&-2&-1.5 \\ 4&5.5&6 \end{bmatrix} = \begin{bmatrix} a_{11}&a_{12}&a_{13} \\ a_{21}&a_{22}&a_{23} \\ a_{31}&a_{32}&a_{33} \end{bmatrix} , \; \begin{bmatrix} a_{21}&a_{22}&a_{23} \end{bmatrix} = ? $

In [9]:
#(1) print `matrix` slicing
matrix_01[1, :]

array([-1. , -2. , -1.5])

#### **(PLUS)** 복소수(complex) 행렬의 표현
#### matrix_02 $ \; = \begin{bmatrix} 1-2i&3+i&1 \\ 1+2i&2-i&7 \end{bmatrix} $

In [10]:
#(1) assign `matrix_02`
matrix_02 = np.array(object=[[1-2j, 3+1j, 1], [1+2j, 2-1j, 7]])
# OR
# matrix_02 = np.array(object=[[complex(real=1, imag=-2), complex(real=3, imag=1), 1], [complex(real=1, imag=2), complex(real=2, imag=-1), 7]])

#(2) print `matrix_02`
matrix_02

array([[1.-2.j, 3.+1.j, 1.+0.j],
       [1.+2.j, 2.-1.j, 7.+0.j]])

## 04. **데이터 타입**

#### 04.1. **타입 확인 : `.dtype`**

In [11]:
#(1) print `matrix_01` dtype
matrix_01.dtype

dtype('float64')

#### 04.2. **명시적 타입 변환 : `.astype()`**

In [12]:
#(1) assign `matrix_03` using astype
matrix_03 = matrix_01.astype(dtype=np.complex128)

#(2) print `matrix_03`
matrix_03

array([[ 1. +0.j,  2.5+0.j,  3. +0.j],
       [-1. +0.j, -2. +0.j, -1.5+0.j],
       [ 4. +0.j,  5.5+0.j,  6. +0.j]])

#### 04.3. **암묵적 타입 변환**

In [13]:
#(1) assign `matrix_04`
matrix_04 = matrix_01 + matrix_03

#(2) print `matrix_04`
matrix_04

array([[ 2.+0.j,  5.+0.j,  6.+0.j],
       [-2.+0.j, -4.+0.j, -3.+0.j],
       [ 8.+0.j, 11.+0.j, 12.+0.j]])

In [14]:
#(3) print `matrix_04` dtype
matrix_04.dtype

dtype('complex128')