## CH2.3. **배열 생성**

## 00. **SET WORK ENVORINMENT**

#### 00.1. **IMPORT PACKAGES AND SET OPTIONS**

In [1]:
import numpy as np

## 01. **항등행렬 생성**

#### 01.1. **정방항등행렬 생성 : `np.identity()`**
#### matrix_01 $ \; = \begin{bmatrix} 1&0&0 \\ 0&1&0 \\ 0&0&1 \end{bmatrix} $

In [2]:
#(1)
matrix_01 = np.identity(n=3, dtype=np.int64)

#(2)
matrix_01

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]], dtype=int64)

#### 01.2. **단위항등행렬 생성 : `np.eye()`**
#### matrix_02 $ \; = \begin{bmatrix} 1&0&0 \\ 0&1&0 \\ 0&0&1 \end{bmatrix} $

In [3]:
#(1)
matrix_02 = np.eye(N=3, M=3, dtype=np.int64)

#(2)
matrix_02

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]], dtype=int64)

#### matrix_03 $ \; = \begin{bmatrix} 0&1&0&0 \\ 0&0&1&0 \\ 0&0&0&1 \end{bmatrix} $

In [4]:
#(1)
matrix_03 = np.eye(N=3, M=4, k=1, dtype=np.int32)

#(2)
matrix_03

array([[0, 1, 0, 0],
       [0, 0, 1, 0],
       [0, 0, 0, 1]])

**(MEMO)** 인자 `K`는 band id라고 정의함

## 02. **삼각행렬 생성**

#### 02.1. **단위 하삼각행렬 생성 : `np.tri()`**
#### matrix_04 $ \; = \begin{bmatrix} 1&0&0 \\ 1&1&0 \\ 1&1&1 \end{bmatrix} $

In [5]:
#(1)
matrix_04 = np.tri(N=3, M=3, k=0, dtype=np.int64)

#(2)
matrix_04

array([[1, 0, 0],
       [1, 1, 0],
       [1, 1, 1]], dtype=int64)

#### 02.2. **기존 데이터 기반 하삼각행렬 생성 : `np.tril()`**
#### matrix_05 $ \; = \begin{bmatrix} 1&0&0&0 \\ 3&2.5&0&0 \\ 1&-3.7&11&0 \end{bmatrix} $

In [6]:
#help(np.tril)

#### 02.3. **기존 데이터 기반 상삼각행렬 생성 : `np.triu()`**
#### matrix_06 $ \; = \begin{bmatrix} 0&1&0&0 \\ 0&0&1&0 \\ 0&0&0&1 \end{bmatrix} $

In [7]:
#help(np.triu)

## 03. **기타 행렬 생성**

#### 03.1. **영행렬 생성 : `np.zeros()`**
#### matrix_07 $ \; = \begin{bmatrix} 0&0&0&0 \\ 0&0&0&0 \\ 0&0&0&0 \end{bmatrix} $

In [8]:
#(1) 
matrix_07 = np.zeros(shape=(3, 4), dtype=np.int64)

#(2)
matrix_07

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]], dtype=int64)

#### 03.2. **모든 성분이 1인 행렬 생성 : `np.ones()`**
#### matrix_08 $ \; = \begin{bmatrix} 1&1&1 \\ 1&1&1 \\ 1&1&1 \end{bmatrix} $

In [9]:
#(1) 
matrix_08 = np.ones(shape=(3, 3), dtype=np.int64)

#(2)
matrix_08

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]], dtype=int64)

#### 03.3. **모든 성분이 특정 값인 행렬 생성 : `np.full()`**
#### matrix_09 $ \; = \begin{bmatrix} 8&8&8&8&8 \\ 8&8&8&8&8 \\ 8&8&8&8&8 \\ 8&8&8&8&8 \\ 8&8&8&8&8 \end{bmatrix} $

In [10]:
#(1) 
matrix_09 = np.full(shape=(5, 5), fill_value=8, dtype=np.int64)

#(2)
matrix_09

array([[8, 8, 8, 8, 8],
       [8, 8, 8, 8, 8],
       [8, 8, 8, 8, 8],
       [8, 8, 8, 8, 8],
       [8, 8, 8, 8, 8]], dtype=int64)

## 04. **난수 기반 행렬 생성**

#### 04.1. **균등분포를 따르는 정수인 행렬 생성 : `np.random.randint()`**
#### matrix_10 $ \; = \begin{bmatrix} a_{11}&a_{12}&a_{13} \\ a_{21}&a_{22}&a_{23} \\ a_{31}&a_{32}&a_{33} \end{bmatrix}, \; a_{ik} \in \{ \mathbb{Z} | 1 \leqq \mathbb{Z} \leqq 10 \}, \; a_{ik} \sim U(0, 10) $

In [31]:
#(1) 
matrix_10 = np.random.randint(low=1, high=10, size=(3,3))

#(2)
matrix_10

array([[2, 1, 3],
       [2, 9, 4],
       [4, 2, 2]])

#### 04.2. **$ 0 $ 과 $ 1 $ 사이의 균등분포를 따르는 실수인 행렬 생성 : `np.random.rand()`**
#### matrix_11 $ \; = \begin{bmatrix} a_{11}&a_{12}&a_{13} \\ a_{21}&a_{22}&a_{23} \\ a_{31}&a_{32}&a_{33} \end{bmatrix}, \; a_{ik} \in \{ \mathbb{R} | 0 \leqq \mathbb{R} \leqq 1 \}, \; a_{ik} \sim U(0, 1) $

In [33]:
#(1)
matrix_11 = np.random.rand(3, 3)

#(2)
matrix_11

array([[0.92411858, 0.85190626, 0.53872993],
       [0.09159682, 0.35512357, 0.47693553],
       [0.47511359, 0.78874067, 0.90164627]])

#### 04.3. **정규분포를 따르는 실수인 행렬 생성 : `np.random.normal()`**
#### matrix_12 $ \; = \begin{bmatrix} a_{11}&a_{12}&a_{13} \\ a_{21}&a_{22}&a_{23} \\ a_{31}&a_{32}&a_{33} \end{bmatrix}, \; a_{ik} \in \{ \mathbb{R} | 0 \leqq \mathbb{R} \leqq 1 \}, \; a_{ik} \sim N(\mu{}, \sigma{}^{2}) $

In [34]:
#(1)
matrix_12 = np.random.normal(loc=0, scale=1, size=(3,3))

#(2)
matrix_12

array([[-1.38226343,  1.486669  , -0.92730207],
       [-0.46740974,  2.39032563,  1.32665404],
       [ 0.68965787,  0.76438453,  0.60479101]])

#### 04.4. **표준정규분포를 따르는 실수인 행렬 생성 : `np.random.randn()`**
#### matrix_13 $ \; = \begin{bmatrix} a_{11}&a_{12}&a_{13} \\ a_{21}&a_{22}&a_{23} \\ a_{31}&a_{32}&a_{33} \end{bmatrix}, \; a_{ik} \in \{ \mathbb{R} | 0 \leqq \mathbb{R} \leqq 1 \}, \; a_{ik} \sim Z(0, 1) $

In [35]:
#(1)
matrix_13 = np.random.randn(3, 3)

#(2)
matrix_13

array([[-1.66133433, -1.09388309,  0.57143761],
       [ 0.65476073, -0.9831928 , -0.81300401],
       [-0.87646218,  0.47863667, -0.5260759 ]])