## CH2.3. **배열 편의기능**

## 00. **SET WORK ENVORINMENT**

#### 00.1. **IMPORT PACKAGES AND SET OPTIONS**

In [2]:
import numpy as np

## 01. **TEMP**

#### 01.1. **TEMP : `np.identity()`**
#### matrix_01 $ \; = \begin{bmatrix} 1&0&0 \\ 0&1&0 \\ 0&0&1 \end{bmatrix} $

In [36]:
#(1)
matrix_01 = np.identity(n=3, dtype=np.int64)

#(2)
matrix_01

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]], dtype=int64)

#### 01.2. **TEMP : `np.eye()`**
#### matrix_02 $ \; = \begin{bmatrix} 1&0&0 \\ 0&1&0 \\ 0&0&1 \end{bmatrix} $

In [37]:
#(1)
matrix_02 = np.eye(N=3, M=3, dtype=np.int64)

#(2)
matrix_02

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]], dtype=int64)

#### matrix_03 $ \; = \begin{bmatrix} 0&1&0&0 \\ 0&0&1&0 \\ 0&0&0&1 \end{bmatrix} $

In [38]:
#(1)
matrix_03 = np.eye(N=3, M=4, k=-1, dtype=np.int32)

#(2)
matrix_03

array([[0, 0, 0, 0],
       [1, 0, 0, 0],
       [0, 1, 0, 0]])

**(MEMO)** 인자 `K`는 band id라고 정의함

## 02. **TEMP**

#### 02.1. **TEMP : `np.tri()`**
#### matrix_04 $ \; = \begin{bmatrix} 0&1&0&0 \\ 0&0&1&0 \\ 0&0&0&1 \end{bmatrix} $

In [43]:
#(1)
matrix_04 = np.tri(N=3, M=3, k=0, dtype=np.int64)

#(2)
matrix_04

array([[1, 0, 0],
       [1, 1, 0],
       [1, 1, 1]], dtype=int64)

#### 02.2. **TEMP : `np.tril()`**
#### matrix_05 $ \; = \begin{bmatrix} 0&1&0&0 \\ 0&0&1&0 \\ 0&0&0&1 \end{bmatrix} $

In [ ]:
#(1)
# matrix_05 = np.triu(N=3, M=3, k=0, dtype=np.int64)

#(2)
# matrix_05

#### 02.3. **TEMP : `np.triu()`**
#### matrix_06 $ \; = \begin{bmatrix} 0&1&0&0 \\ 0&0&1&0 \\ 0&0&0&1 \end{bmatrix} $

In [75]:
#(1)
# matrix_05 = np.triu(N=3, M=3, k=0, dtype=np.int64)

#(2)
# matrix_05

## 03. **TEMP**

#### 03.1. **TEMP : `np.zeros()`**

In [44]:
pass

#### 03.2. **TEMP : `np.ones()`**

In [ ]:
pass

#### 03.3. **TEMP : `np.full()`**

In [ ]:
pass

## 04. **TEMP**

#### 04.1. **TEMP : `np.random.randint()`**

In [66]:
np.random.randint(low=1, high=10, size=(3,3))

array([[1, 1, 2],
       [3, 3, 1],
       [7, 2, 1]])

#### 04.2. **TEMP : `np.random.rand()`**

In [56]:
np.random.rand(3, 3)

array([[0.96648827, 0.73922265, 0.23898201],
       [0.86088393, 0.68811498, 0.49860028],
       [0.96293203, 0.17214176, 0.49224475]])

#### 04.3. **TEMP : `np.random.normal()`**

In [73]:
np.random.normal(loc=0, scale=1, size=(3,3))

array([[ 0.02098166, -1.85229046,  0.73633372],
       [ 0.05836128, -0.27817582, -0.77997102],
       [ 0.87626344, -1.56450197, -1.07406879]])

#### 04.4. **TEMP : `np.random.randn()`**

In [72]:
np.random.randn(3, 3)

array([[ 2.2963575 , -0.13082686, -0.68936657],
       [-1.2128498 ,  0.23532324,  0.69651487],
       [-1.28241608, -1.0126063 , -1.00709055]])