## CH2.3. **배열 생성**

## 00. **SET WORK ENVORINMENT**

#### 00.1. **IMPORT PACKAGES AND SET OPTIONS**

In [1]:
import numpy as np

## 01. **항등행렬 생성**

#### 01.1. **정방항등행렬 생성 : `np.identity()`**
#### matrix_01 $ \; = \begin{bmatrix} 1&0&0 \\ 0&1&0 \\ 0&0&1 \end{bmatrix} $

In [2]:
#(1)
matrix_01 = np.identity(n=3, dtype=np.int64)

#(2)
matrix_01

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]], dtype=int64)

#### 01.2. **항등행렬 생성 : `np.eye()`**
#### matrix_02 $ \; = \begin{bmatrix} 1&0&0 \\ 0&1&0 \\ 0&0&1 \end{bmatrix} $

In [3]:
#(1)
matrix_02 = np.eye(N=3, M=3, dtype=np.int64)

#(2)
matrix_02

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]], dtype=int64)

#### matrix_03 $ \; = \begin{bmatrix} 0&1&0&0 \\ 0&0&1&0 \\ 0&0&0&1 \end{bmatrix} $

In [4]:
#(1)
matrix_03 = np.eye(N=3, M=4, k=1, dtype=np.int32)

#(2)
matrix_03

array([[0, 1, 0, 0],
       [0, 0, 1, 0],
       [0, 0, 0, 1]])

**(MEMO)** 인자 `K`는 band id라고 정의함

## 02. **삼각행렬 생성**

#### 02.1. **단위 하삼각행렬 생성 : `np.tri()`**
#### matrix_04 $ \; = \begin{bmatrix} 1&0&0 \\ 1&1&0 \\ 1&1&1 \end{bmatrix} $

In [5]:
#(1)
matrix_04 = np.tri(N=3, M=3, k=0, dtype=np.int64)

#(2)
matrix_04

array([[1, 0, 0],
       [1, 1, 0],
       [1, 1, 1]], dtype=int64)

#### 02.2. **기존 데이터 기반 하삼각행렬 생성 : `np.tril()`**
#### matrix_05 $ \; = \begin{bmatrix} 1&0&0&0 \\ 3&2.5&0&0 \\ 1&-3.7&11&0 \end{bmatrix} $

In [15]:
#(1)
matrix_05 = np.tril(m=[[1, 3, 4, 5], [3, 2.5, -7, 3], [1, -3.7, 11, 1]], k=0)
# matrix_05 = np.triu(N=3, M=3, k=0, dtype=np.int64)

#(2)
matrix_05

array([[ 1. ,  0. ,  0. ,  0. ],
       [ 3. ,  2.5,  0. ,  0. ],
       [ 1. , -3.7, 11. ,  0. ]])

In [10]:
np.tril([[1,2,3],[4,5,6],[7,8,9],[10,11,12]], 0)

array([[ 1,  0,  0],
       [ 4,  5,  0],
       [ 7,  8,  9],
       [10, 11, 12]])

#### 02.3. **기존 데이터 기반 상삼각행렬 생성 : `np.triu()`**
#### matrix_06 $ \; = \begin{bmatrix} 0&1&0&0 \\ 0&0&1&0 \\ 0&0&0&1 \end{bmatrix} $

In [ ]:
#(1)
# matrix_05 = np.triu(N=3, M=3, k=0, dtype=np.int64)

#(2)
# matrix_05

## 03. **TEMP**

#### 03.1. **TEMP : `np.zeros()`**

In [18]:
np.zeros(shape=(3,3), dtype=np.int64)

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]], dtype=int64)

#### 03.2. **TEMP : `np.ones()`**

In [ ]:
pass

#### 03.3. **TEMP : `np.full()`**

In [ ]:
pass

## 04. **TEMP**

#### 04.1. **TEMP : `np.random.randint()`**

In [ ]:
np.random.randint(low=1, high=10, size=(3,3))

#### 04.2. **TEMP : `np.random.rand()`**

In [ ]:
np.random.rand(3, 3)

#### 04.3. **TEMP : `np.random.normal()`**

In [ ]:
np.random.normal(loc=0, scale=1, size=(3,3))

#### 04.4. **TEMP : `np.random.randn()`**

In [ ]:
np.random.randn(3, 3)