## CH2.3. **기본 배열 생성**

## 00. **SET WORK ENVORINMENT**

#### 00.1. **IMPORT PACKAGES AND SET OPTIONS**

In [1]:
import numpy as np

<b></b>

## 01. **항등행렬 생성**

#### 01.1. **정방항등행렬 생성 : `np.identity()`**
#### matrix_01 $ \; = \begin{bmatrix} 1&0&0 \\ 0&1&0 \\ 0&0&1 \end{bmatrix} $

In [2]:
#(1) Define `matrix_01`
matrix_01 = np.identity(n=3, dtype=np.int64)

#(2) Print `matrix_01`
matrix_01

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]], dtype=int64)

#### 01.2. **단위항등행렬 생성 : `np.eye()`**
#### matrix_02 $ \; = \begin{bmatrix} 1&0&0 \\ 0&1&0 \\ 0&0&1 \end{bmatrix} $

In [3]:
#(1) Define `matrix_02`
matrix_02 = np.eye(N=3, M=3, dtype=np.int64)

#(2) Print `matrix_02`
matrix_02

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]], dtype=int64)

#### matrix_03 $ \; = \begin{bmatrix} 0&1&0&0 \\ 0&0&1&0 \\ 0&0&0&1 \end{bmatrix} $

In [4]:
#(1) Define `matrix_03`
matrix_03 = np.eye(N=3, M=4, k=1, dtype=np.int32)

#(2) Print `matrix_03`
matrix_03

array([[0, 1, 0, 0],
       [0, 0, 1, 0],
       [0, 0, 0, 1]])

**(MEMO)** 인자 `K`는 band id라고 정의함

## 02. **삼각행렬 생성**

#### 02.1. **단위 하삼각행렬 생성 : `np.tri()`**
#### matrix_04 $ \; = \begin{bmatrix} 1&0&0 \\ 1&1&0 \\ 1&1&1 \end{bmatrix} $

In [5]:
#(1) Define `matrix_04`
matrix_04 = np.tri(N=3, M=3, k=0, dtype=np.int64)

#(2) Print `matrix_04`
matrix_04

array([[1, 0, 0],
       [1, 1, 0],
       [1, 1, 1]], dtype=int64)

#### 02.2. **기존 데이터 기반 하삼각행렬 생성 : `np.tril()`**
#### matrix_05 $ \; = \begin{bmatrix} 1&3&2&6 \\ 3&2.5&4&-3 \\ 1&-3.7&11&-2 \end{bmatrix}, \; $ matrix_06 $ \; = \begin{bmatrix} 1&0&0&0 \\ 3&2.5&0&0 \\ 1&-3.7&11&0 \end{bmatrix} $

In [6]:
#(1) Define `matrix_05`
matrix_05 = np.array(object=[[1, 3, 2, 6], [3, 2.5, 4, -3], [1, -3.7, 11, -2]])

#(2) Print `matrix_05`
matrix_05

array([[ 1. ,  3. ,  2. ,  6. ],
       [ 3. ,  2.5,  4. , -3. ],
       [ 1. , -3.7, 11. , -2. ]])

In [7]:
#(1) Define `matrix_06`
matrix_06 = np.tril(m=matrix_05, k=0)

#(2) Print `matrix_06`
matrix_06

array([[ 1. ,  0. ,  0. ,  0. ],
       [ 3. ,  2.5,  0. ,  0. ],
       [ 1. , -3.7, 11. ,  0. ]])

#### 02.3. **기존 데이터 기반 상삼각행렬 생성 : `np.triu()`**
#### matrix_05 $ \; = \begin{bmatrix} 1&3&2&6 \\ 3&2.5&4&-3 \\ 1&-3.7&11&-2 \end{bmatrix}, \; $ matrix_07 $ \; = \begin{bmatrix} 0&3&2&6 \\ 0&0&4&-3 \\ 0&0&0&-2 \end{bmatrix} $

In [8]:
#(1) Define `matrix_07`
matrix_07 = np.triu(m=matrix_05, k=1)

#(2) Print `matrix_07`
matrix_07

array([[ 0.,  3.,  2.,  6.],
       [ 0.,  0.,  4., -3.],
       [ 0.,  0.,  0., -2.]])

## 03. **기타 행렬 생성**

#### 03.1. **영행렬 생성 : `np.zeros()`**
#### matrix_08 $ \; = \begin{bmatrix} 0&0&0&0 \\ 0&0&0&0 \\ 0&0&0&0 \end{bmatrix} $

In [9]:
#(1) Define `matrix_08`
matrix_08 = np.zeros(shape=(3, 4), dtype=np.int64)

#(2) Print `matrix_08`
matrix_08

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]], dtype=int64)

#### 03.2. **모든 성분이 1인 행렬 생성 : `np.ones()`**
#### matrix_09 $ \; = \begin{bmatrix} 1&1&1 \\ 1&1&1 \\ 1&1&1 \end{bmatrix} $

In [10]:
#(1) Define `matrix_09`
matrix_09 = np.ones(shape=(3, 3), dtype=np.int64)

#(2) Print `matrix_09`
matrix_09

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]], dtype=int64)

#### 03.3. **모든 성분이 특정 값인 행렬 생성 : `np.full()`**
#### matrix_10 $ \; = \begin{bmatrix} 8&8&8&8&8 \\ 8&8&8&8&8 \\ 8&8&8&8&8 \\ 8&8&8&8&8 \\ 8&8&8&8&8 \end{bmatrix} $

In [11]:
#(1) Define `matrix_10`
matrix_10 = np.full(shape=(5, 5), fill_value=8, dtype=np.int64)

#(2) Print `matrix_10`
matrix_10

array([[8, 8, 8, 8, 8],
       [8, 8, 8, 8, 8],
       [8, 8, 8, 8, 8],
       [8, 8, 8, 8, 8],
       [8, 8, 8, 8, 8]], dtype=int64)

## 04. **난수 기반 행렬 생성**

#### 04.1. **균등분포를 따르는 정수인 행렬 생성 : `np.random.randint()`**
#### matrix_11 $ \; = \begin{bmatrix} a_{11}&a_{12}&a_{13} \\ a_{21}&a_{22}&a_{23} \\ a_{31}&a_{32}&a_{33} \end{bmatrix}, \; a_{ik} \in \{ \mathbb{Z} | 1 \leqq \mathbb{Z} \leqq 10 \}, \; a_{ik} \sim U(0, 10) $

In [12]:
#(1) Define `matrix_11`
matrix_11 = np.random.randint(low=1, high=10, size=(3,3))

#(2) Print `matrix_11`
matrix_11

array([[3, 1, 2],
       [4, 2, 4],
       [8, 7, 9]])

#### 04.2. **$ 0 $ 과 $ 1 $ 사이의 균등분포를 따르는 실수인 행렬 생성 : `np.random.rand()`**
#### matrix_12 $ \; = \begin{bmatrix} a_{11}&a_{12}&a_{13} \\ a_{21}&a_{22}&a_{23} \\ a_{31}&a_{32}&a_{33} \end{bmatrix}, \; a_{ik} \in \{ \mathbb{R} | 0 \leqq \mathbb{R} \leqq 1 \}, \; a_{ik} \sim U(0, 1) $

In [13]:
#(1) Define `matrix_12`
matrix_12 = np.random.rand(3, 3)

#(2) Print `matrix_12`
matrix_12

array([[0.32077954, 0.7863974 , 0.38489264],
       [0.44107245, 0.29942582, 0.09202386],
       [0.09819842, 0.810557  , 0.23210126]])

#### 04.3. **정규분포를 따르는 실수인 행렬 생성 : `np.random.normal()`**
#### matrix_13 $ \; = \begin{bmatrix} a_{11}&a_{12}&a_{13} \\ a_{21}&a_{22}&a_{23} \\ a_{31}&a_{32}&a_{33} \end{bmatrix}, \; a_{ik} \in \{ \mathbb{R} | 0 \leqq \mathbb{R} \leqq 1 \}, \; a_{ik} \sim N(\mu{}, \sigma{}^{2}) $

In [14]:
#(1) Define `matrix_13`
matrix_13 = np.random.normal(loc=0, scale=1, size=(3,3))

#(2) Print `matrix_13`
matrix_13

array([[ 0.41887723, -1.05082642,  1.06610084],
       [ 1.15730673,  1.49393094,  0.76923846],
       [-0.81604791, -1.13523085,  2.3068664 ]])

#### 04.4. **표준정규분포를 따르는 실수인 행렬 생성 : `np.random.randn()`**
#### matrix_14 $ \; = \begin{bmatrix} a_{11}&a_{12}&a_{13} \\ a_{21}&a_{22}&a_{23} \\ a_{31}&a_{32}&a_{33} \end{bmatrix}, \; a_{ik} \in \{ \mathbb{R} | 0 \leqq \mathbb{R} \leqq 1 \}, \; a_{ik} \sim Z(0, 1) $

In [15]:
#(1) Define `matrix_14`
matrix_14 = np.random.randn(3, 3)

#(2) Print `matrix_14`
matrix_14

array([[-0.85515739, -1.48063923,  0.37273011],
       [-0.77476872, -1.63709762, -1.21583217],
       [ 1.06417481,  0.99302683,  0.27619937]])