## CH2.4. **배열 조작**

## 00. **SET WORK ENVORINMENT**

#### 00.1. **IMPORT PACKAGES AND SET OPTIONS**

In [1]:
import numpy as np

<b></b>

## 01. **배열 복사**

#### 01.1. **배열 복사 : `.copy()`**
#### matrix_01 $ \; = \begin{bmatrix} 1&2&3 \\ 2&3&1 \\ 3&4&6 \end{bmatrix}, \; $ matrix_02 $ \; = $ matrix_01 $ \; = \begin{bmatrix} 1&2&3 \\ 2&3&1 \\ 3&4&6 \end{bmatrix} $

In [2]:
#(1) Define `matrix_01`
matrix_01 = np.array(object=[[1, 2, 3], [2, 3, 1], [3, 4, 6]], dtype=np.int64)

#(2) Print `matrix_01`
matrix_01

array([[1, 2, 3],
       [2, 3, 1],
       [3, 4, 6]], dtype=int64)

In [3]:
#(3) Copy `matrix_01`
matrix_02 = matrix_01.copy()

#(4) Print `matrix_02`
matrix_02

array([[1, 2, 3],
       [2, 3, 1],
       [3, 4, 6]], dtype=int64)

#### **(PLUS)** 바로 변수를 할당하는 경우, 같은 메모리(공간)을 참조하기 때문에 영향을 받음

In [4]:
#(1) Define `matrix_03`
matrix_03 = matrix_01 

#(2) Print `matrix_03`
matrix_03

array([[1, 2, 3],
       [2, 3, 1],
       [3, 4, 6]], dtype=int64)

In [5]:
#(3) Modify entry of `matrix_03` 
matrix_03[0, 0] = 32

#(4) Print `matrix_03`
matrix_03

array([[32,  2,  3],
       [ 2,  3,  1],
       [ 3,  4,  6]], dtype=int64)

In [6]:
#(5) Print `matrix_01`
matrix_01

array([[32,  2,  3],
       [ 2,  3,  1],
       [ 3,  4,  6]], dtype=int64)

## 02. **배열 형태 변환**

#### 02.1. **배열 n차원 변환 : `np.reshape()`**
#### matrix_04 $ \; = \begin{bmatrix} 1&2&3&2 \\ 2&3&1&4 \\ 3&4&6&8 \end{bmatrix}, \; $ matrix_05 $ \; = \begin{bmatrix} 1&2&3&2&2&3 \\ 1&4&3&4&6&8 \end{bmatrix} $

In [7]:
#(1) Define `matrix_04`
matrix_04 = np.array(object=[[1, 2, 3, 2], [2, 3, 1, 4], [3, 4, 6, 8]], dtype=np.int64)

#(2) Print `matrix_04`
matrix_04

array([[1, 2, 3, 2],
       [2, 3, 1, 4],
       [3, 4, 6, 8]], dtype=int64)

In [8]:
#(3) Define `matrix_05`
matrix_05 = np.reshape(a=matrix_04.copy(), newshape=(2, 6))

#(4) Print `matrix_05`
matrix_05

array([[1, 2, 3, 2, 2, 3],
       [1, 4, 3, 4, 6, 8]], dtype=int64)

#### 02.2. **배열 전치 : `.transpose()`**
#### matrix_04 $ \; = \begin{bmatrix} 1&2&3&2 \\ 2&3&1&4 \\ 3&4&6&8 \end{bmatrix}, \; $ matrix_06 $ \; = $ matrix_04 $^{T} \; = \begin{bmatrix} 1&2&3 \\ 2&3&4 \\ 3&1&6 \\ 2&4&8 \end{bmatrix} $

In [9]:
#(1) Transpose `matrix_04`
matrix_06 = matrix_04.transpose()

#(2) Print `matrix_05`
matrix_06

array([[1, 2, 3],
       [2, 3, 4],
       [3, 1, 6],
       [2, 4, 8]], dtype=int64)

#### 02.3. **1차원 벡터 변환 : `.flatten()`**
#### matrix_04 $ \; = \begin{bmatrix} 1&2&3&2 \\ 2&3&1&4 \\ 3&4&6&8 \end{bmatrix}, \; $ vector_01 $ \; = \begin{bmatrix} 1&2&3&2&2&3&\cdots{}&6&8 \end{bmatrix} $

In [10]:
#(1) Define `vector_01`
vector_01 = matrix_04.flatten()

#(2) Print `vector_01`
vector_01

array([1, 2, 3, 2, 2, 3, 1, 4, 3, 4, 6, 8], dtype=int64)

#### **(PLUS)** `.flatten()` 메서드는 `np.ravel()` 함수와 동일한 결과를 반환함

In [11]:
#(1) Define `vector_02`
vector_02 = np.ravel(a=matrix_04)

#(2) Print `vector_02`
vector_02

array([1, 2, 3, 2, 2, 3, 1, 4, 3, 4, 6, 8], dtype=int64)

## 02. **대각 성분 조작**

#### 02.1. **대각 성분 반환 : `np.diag()`**
#### matrix_04 $ \; = \begin{bmatrix} 1&2&3&2 \\ 2&3&1&4 \\ 3&4&6&8 \end{bmatrix}, \; \begin{bmatrix} a_{11} \\ a_{22} \\ a_{23} \end{bmatrix} = ? $

In [12]:
#(1) Print diagonal entry of `matrix_04` 
np.diag(v=matrix_04, k=0)

array([1, 3, 6], dtype=int64)

#### 02.2. **대각 성분 합 반환 : `np.trace()`**
#### matrix_04 $ \; = \begin{bmatrix} 1&2&3&2 \\ 2&3&1&4 \\ 3&4&6&8 \end{bmatrix}, \; a_{11}+a_{22}+a_{23} = ? $

In [13]:
#(1) Print diagonal entry sum of `matrix_04`
np.trace(a=matrix_04)

10

#### 02.3. **정방대각행렬 생성 : `np.diagflat()`**
#### matrix_07 = $ \begin{bmatrix} 1&0&0&0 \\ 0&2&0&0 \\ 0&0&6&0 \\ 0&0&0&7 \end{bmatrix} $

In [14]:
#(1) Define `matrix_07`
matrix_07 = np.diagflat(v=[1, 2, 6, 7], k=0)

#(2) Print `matrix_07`
matrix_07

array([[1, 0, 0, 0],
       [0, 2, 0, 0],
       [0, 0, 6, 0],
       [0, 0, 0, 7]])

## 04. **배열 결합**

#### 04.1. **수평 배열 결합 : `np.hstack()`**
#### matrix_08 $ \; = \begin{bmatrix} \text{matrix\_01} & \text{matrix\_02} \end{bmatrix} $

In [15]:
#(1) Define `matrix_08`
matrix_08 = np.hstack(tup=(matrix_01, matrix_02))

#(2) Print `matrix_08`
matrix_08

array([[32,  2,  3,  1,  2,  3],
       [ 2,  3,  1,  2,  3,  1],
       [ 3,  4,  6,  3,  4,  6]], dtype=int64)

#### 04.2. **수직 배열 결합 : `np.vstack()`**
#### matrix_09 $ \; = \begin{bmatrix} \text{matrix\_01} \\ \text{matrix\_02} \end{bmatrix} $

In [16]:
#(1) Define `matrix_09`
matrix_09 = np.vstack(tup=(matrix_01, matrix_02))

#(2) Print `matrix_09`
matrix_09

array([[32,  2,  3],
       [ 2,  3,  1],
       [ 3,  4,  6],
       [ 1,  2,  3],
       [ 2,  3,  1],
       [ 3,  4,  6]], dtype=int64)

## 05. **배열 값 반환**

#### 05.1. **실수부반환 : `.real`**
#### matrix_10 = $ \begin{bmatrix} 1+2i&3&-4i \\ 1-3j&2&0 \\ 0&i&3+6i \end{bmatrix}, \; \_ $

In [17]:
#(1) Define `matrix_10`
matrix_10 = np.array(object=[[1+2j, 3, -4j], [1-3j, 2, 0], [0, 1j, 3+6j]], dtype=np.complex128)

#(2) Print `matrix_10`
matrix_10

array([[ 1.+2.j,  3.+0.j, -0.-4.j],
       [ 1.-3.j,  2.+0.j,  0.+0.j],
       [ 0.+0.j,  0.+1.j,  3.+6.j]])

In [18]:
#(3) Print real Number of `matrix_10`
matrix_10.real

array([[ 1.,  3., -0.],
       [ 1.,  2.,  0.],
       [ 0.,  0.,  3.]])

#### 05.2. **허수부 반환 : `.imag`**
#### matrix_10 = $ \begin{bmatrix} 1+2i&3&-4i \\ 1-3j&2&0 \\ 0&i&3+6i \end{bmatrix}, \; \_ $

In [19]:
#(1) Print complex number of `matrix_10`
matrix_10.imag

array([[ 2.,  0., -4.],
       [-3.,  0.,  0.],
       [ 0.,  1.,  6.]])

#### 05.3. **허수부 복소켤레 반환 : `.conjugate()`**
#### matrix_10 = $ \begin{bmatrix} 1+2i&3&-4i \\ 1-3j&2&0 \\ 0&i&3+6i \end{bmatrix}, \; \_ $

In [21]:
#(1) Print complex conjugate of `matrix_10`
matrix_10.conjugate()

array([[ 1.-2.j,  3.-0.j, -0.+4.j],
       [ 1.+3.j,  2.-0.j,  0.-0.j],
       [ 0.-0.j,  0.-1.j,  3.-6.j]])