## CH2.5. **배열 연산**

## 00. **SET WORK ENVORINMENT**

#### 00.1. **IMPORT PACKAGES AND SET OPTIONS**

In [2]:
import numpy as np

<b></b>

## 01. **배열의 합**

#### 01.1. **스칼라 합**

In [5]:
#(1)
matrix_01 = np.array(object=[[1, 3, -5], [2, 0, -4], [3, 2, 1]], dtype=np.int64)

#(2)
matrix_01

array([[ 1,  3, -5],
       [ 2,  0, -4],
       [ 3,  2,  1]], dtype=int64)

In [6]:
#(3)
matrix_01 + 3

array([[ 4,  6, -2],
       [ 5,  3, -1],
       [ 6,  5,  4]], dtype=int64)

#### **(PLUS)** 브로드 캐스팅(Broad Casting)
#### 더 작은 배열을 자동으로 더 큰 배열의 크기에 맞춰 확장

#### 01.2. **벡터 합**

In [9]:
#(1)
vector_01 = np.array(object=[-3, 2, 0])

#(2) 
vector_01

array([-3,  2,  0])

In [10]:
#(3) 
matrix_01 + vector_01

array([[-2,  5, -5],
       [-1,  2, -4],
       [ 0,  4,  1]], dtype=int64)

**(MEMO)** 두 배열의 사이즈들의 값 중 한 개라도 일치하면 연산이 되지만, 그렇지 않으면 연산되지 않음

In [25]:
#(1)
vector_02 = np.array(object=[1, 3], dtype=np.int64)

#(2)
try : 
    matrix_01 + vector_02
except ValueError as error : 
    print(f'>> AN ERROR OCCURRED. ERROR MESSAGE IS "{error}".')

>> AN ERROR OCCURRED. ERROR MESSAGE IS "operands could not be broadcast together with shapes (3,3) (2,) ".


## 02. **배열의 곱**

#### 02.1. **스칼라 곱**

In [23]:
#(1)
matrix_01 * 3

array([[  3,   9, -15],
       [  6,   0, -12],
       [  9,   6,   3]], dtype=int64)

#### 01.4. **행렬 곱**

In [ ]:
#(1)
matrix_02 