## CH2.5. **배열 연산**

## 00. **SET WORK ENVORINMENT**

#### 00.1. **IMPORT PACKAGES AND SET OPTIONS**

In [1]:
import numpy as np

<b></b>

## 01. **배열의 합**

#### **01.1.** 브로드 캐스팅(Broad Casting) : 
#### **(1)** 더 작은 배열을 자동으로 더 큰 배열의 크기에 맞춰 확장하는 메커니즘
#### **(2)** 연산기호 `*`을 이용하면 브로드캐스팅을 이용하여 연산 처리

#### 01.2. **행렬-스칼라 합 (By broad-casting)**
#### matrix_01 $ \; = \begin{bmatrix} 1&3&-5 \\ 2&0&-4 \\ 3&2&1 \end{bmatrix}, \; \begin{bmatrix} 3&3&3 \\ 3&3&3 \\ 3&3&3 \end{bmatrix} + $ matrix_01 $ = ? $

In [2]:
#(1) Define `matrix_01`
matrix_01 = np.array(object=[[1, 3, -5], [2, 0, -4], [3, 2, 1]], dtype=np.int64)

#(2) Print `matrix_01`
matrix_01

array([[ 1,  3, -5],
       [ 2,  0, -4],
       [ 3,  2,  1]], dtype=int64)

In [3]:
#(3) Print `matrix_01` + 3
matrix_01 + 3

array([[ 4,  6, -2],
       [ 5,  3, -1],
       [ 6,  5,  4]], dtype=int64)

#### 01.3. **행렬-벡터 합 (By broad-casting)**
#### matrix_01 $ \; = \begin{bmatrix} 1&3&-5 \\ 2&0&-4 \\ 3&2&1 \end{bmatrix}, \; $ vector_01 $ \; = \begin{bmatrix} -3&2&0 \end{bmatrix}, \; \begin{bmatrix} \text{vector\_01} \\ \text{vector\_01} \\ \text{vector\_01} \end{bmatrix} + $ matrix_01 $ = ? $

In [4]:
#(1) Define `vector_01`
vector_01 = np.array(object=[-3, 2, 0])

#(2) Print `vector_01`
vector_01

array([-3,  2,  0])

In [5]:
#(3) Print `matrix_01` + `vector_01`
matrix_01 + vector_01

array([[-2,  5, -5],
       [-1,  2, -4],
       [ 0,  4,  1]], dtype=int64)

**(MEMO)** 두 배열의 사이즈들의 값 중 한 개라도 일치하면 연산이 되지만, 그렇지 않으면 연산되지 않음

In [6]:
#(1) Define `vector_02`
vector_02 = np.array(object=[1, 3], dtype=np.int64)

#(2) Print `vector_01` + `vector_02`
try : 
    matrix_01 + vector_02
except ValueError as error : 
    print(f'>> AN ERROR OCCURRED. ERROR MESSAGE IS "{error}".')

>> AN ERROR OCCURRED. ERROR MESSAGE IS "operands could not be broadcast together with shapes (3,3) (2,) ".


#### 01.4. **행렬-행렬 합**
#### matrix_01 $ \; = \begin{bmatrix} 1&3&-5 \\ 2&0&-4 \\ 3&2&1 \end{bmatrix}, \; $ matrix_02 $ \; = \begin{bmatrix} 3&0&2 \\ 2&0&0 \\ 1.1&-3&6.5 \end{bmatrix}, \; $ matrix_01 $ + $ matrix_02 $ = ? $

In [7]:
#(1) Define `matrix_02`
matrix_02 = np.array(object=[[3, 0, 2], [2, 0, 0], [1.1, -3, 6.5]])

#(2) Print `matrix_02`
matrix_02

array([[ 3. ,  0. ,  2. ],
       [ 2. ,  0. ,  0. ],
       [ 1.1, -3. ,  6.5]])

In [8]:
#(3) Print `matrix_01` + `matrix_02`
matrix_01 + matrix_02

array([[ 4. ,  3. , -3. ],
       [ 4. ,  0. , -4. ],
       [ 4.1, -1. ,  7.5]])

## 02. **배열의 곱**

#### 02.1. **행렬-스칼라 곱**
#### matrix_01 $ \; = \begin{bmatrix} 1&3&-5 \\ 2&0&-4 \\ 3&2&1 \end{bmatrix}, \; 3 \times{} $ matrix_01 $ = ? $

In [9]:
#(1) Print 3 * `matrix_01`
3 * matrix_01

array([[  3,   9, -15],
       [  6,   0, -12],
       [  9,   6,   3]], dtype=int64)

#### 02.3. **행렬-벡터 곱 : `np.matmul()` or `@`**
#### matrix_01 $ \; = \begin{bmatrix} 1&3&-5 \\ 2&0&-4 \\ 3&2&1 \end{bmatrix}, \; $ vector_01 $ \; = \begin{bmatrix} -3&2&0 \end{bmatrix}, \; $ vector_01 $ \times{} $ matrix_01 $ = ? $

In [10]:
#(1) Print `vector_01` * `matrix_01`
vector_01 @ matrix_01

array([ 1, -9,  7], dtype=int64)

In [11]:
#(2) Print `vector_01` * `matrix_01`
np.matmul(vector_01, matrix_01)

array([ 1, -9,  7], dtype=int64)

#### 02.3. **행렬-행렬 곱 : `np.matmul()` or `@`**
#### matrix_01 $ \; = \begin{bmatrix} 1&3&-5 \\ 2&0&-4 \\ 3&2&1 \end{bmatrix}, \; $ matrix_02 $ \; = \begin{bmatrix} 3&0&2 \\ 2&0&0 \\ 1.1&-3&6.5 \end{bmatrix}, \; $ matrix_01 $ \times() $ matrix_02 $ = ? $

In [12]:
#(1) Print `matrix_01` @ `matrix_02``
matrix_01 @ matrix_02

array([[  3.5,  15. , -30.5],
       [  1.6,  12. , -22. ],
       [ 14.1,  -3. ,  12.5]])

In [13]:
#(2) Print `matrix_01` @ `matrix_02``
np.matmul(matrix_01, matrix_02)

array([[  3.5,  15. , -30.5],
       [  1.6,  12. , -22. ],
       [ 14.1,  -3. ,  12.5]])

#### **(PLUS)** 브로드캐스팅을 이용할 경우

In [14]:
#(1) Print `matrix_01` * `matrix_02`
matrix_01 * matrix_02

array([[  3. ,   0. , -10. ],
       [  4. ,   0. ,  -0. ],
       [  3.3,  -6. ,   6.5]])

## 03. **배열의 기타 연산**

#### 03.1. **내적(Inner product) : `np.vdot()`**
#### matrix_01 $ \; = \begin{bmatrix} 1&3&-5 \\ 2&0&-4 \\ 3&2&1 \end{bmatrix} = \begin{bmatrix} a_{11}&a_{12}&a_{13} \\ a_{21}&a_{22}&a_{23} \\ a_{31}&a_{32}&a_{33} \end{bmatrix}, \; $ matrix_02 $ \; = \begin{bmatrix} 3&0&2 \\ 2&0&0 \\ 1.1&-3&6.5 \end{bmatrix} = \begin{bmatrix} b_{11}&b_{12}&b_{13} \\ b_{21}&b_{22}&b_{23} \\ b_{31}&b_{32}&b_{33} \end{bmatrix} $
#### $ \sum{}_{i=1}^{3}\sum{}_{k=1}^{3} a_{ik}b_{ik} = ? $

In [15]:
#(1) Print inner product of `matrix_01` and `matrix_02`
np.vdot(matrix_01, matrix_02)

0.8000000000000007

#### 03.2. **외적-벡터곱(Cross product) : `np.cross()`**
#### vector_01 $ \; = \begin{bmatrix} -3&2&0 \end{bmatrix}, \; $ vector_03 $ \; = \begin{bmatrix} 0&8&2 \end{bmatrix}, \; $ vector_01 $ \times{} $ vector_03 $ = ? $

In [16]:
#(1) Define `vector_03`
vector_03 = np.array(object=[0, 8, 2])

#(2) Print `vector_03`
vector_03

array([0, 8, 2])

In [17]:
#(3) Print cross-product of `vector_01` and `vector_02`
np.cross(a=vector_01, b=vector_02)

array([  0,   0, -11], dtype=int64)

#### 03.3. **외적-텐서곱(Outer Product) : `np.outer()`**
#### vector_01 $ \; = \begin{bmatrix} -3&2&0 \end{bmatrix}, \; $ vector_03 $ \; = \begin{bmatrix} 0&8&2 \end{bmatrix}, \; $ vector_01 $ \otimes{} $ vector_03 $ = ? $

In [18]:
#(1) Print outer-product of `vector_01` and `vector_02`
np.outer(a=vector_01, b=vector_02)

array([[-3, -9],
       [ 2,  6],
       [ 0,  0]], dtype=int64)

## 04. **벡터의 길이 ; 놈(Norm)**

#### 04.1. **맨하탄 놈(Manhattan norm); L1 놈**
#### L1 Norm $ \; = \lVert{} \textbf{x} \rVert{}_{1} = \sum{}_{i=1}^{n} |\textbf{x}_{i} |, \; \lVert{} \text{vector\_01} \rVert{}_{1} = ? $

In [19]:
#(1) Print l1-norm of `vector_01`
np.linalg.norm(x=vector_01, ord=1)

5.0

#### 04.2. **유클라디안 놈(Euclidean); L2 놈**
#### L2 Norm $ \; = \lVert{} \textbf{x} \rVert{}_{2} = \sum{}_{i=1}^{n} |\textbf{x}_{i} |, \; \lVert{} \text{vector\_01} \rVert{}_{2} = ? $

In [20]:
#(2) Print l2-norm of `vector_01`
np.linalg.norm(x=vector_01, ord=2)

3.605551275463989